[package]
name = "lojix-nexus"
version = "1.0.1"
edition = "2024"
rust-version = "1.89"
publish = false

[[bin]]
name = "lojix-nexus"
path = "src/main.rs"

[dependencies]
lojix = { path = "..", default-features = false }

[dev-dependencies]
meta-signal-lojix = { git = "https://github.com/LiGoldragon/meta-signal-lojix", rev = "683ad0421580add419bb3ab33c9ecd6abe62eecd" }
signal-lojix = { git = "https://github.com/LiGoldragon/signal-lojix", rev = "90933a46a66adc3d272fd5ce780091eab784f0ab" }
tempfile = "3"
triad-runtime = { git = "https://github.com/LiGoldragon/triad-runtime.git", branch = "main" }
rustix = { version = "1", default-features = false, features = ["process"] }

[lints.rust]
unsafe_code = "forbid"
