[package]
name = "lojix-nexus"
version = "1.0.1"
edition = "2024"
rust-version = "1.89"
publish = false

[[bin]]
name = "lojix-nexus"
path = "src/main.rs"

[dependencies]
lojix = { path = "..", default-features = false }

[dev-dependencies]
meta-signal-lojix = { git = "https://github.com/LiGoldragon/meta-signal-lojix", rev = "901e5da6c8a58993479b7ba2ed1d0d62908d53b1" }
signal-lojix = { git = "https://github.com/LiGoldragon/signal-lojix", rev = "3a57717e5a09591aecbaafd88bd138647a1d872d" }
tempfile = "3"
triad-runtime = { git = "https://github.com/LiGoldragon/triad-runtime.git", branch = "main" }
rustix = { version = "1", default-features = false, features = ["process"] }

[lints.rust]
unsafe_code = "forbid"
