// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use signal_lojix::schema::lib::Input as OrdinaryInput;
pub use signal_lojix::schema::lib::Output as OrdinaryOutput;
pub use meta_signal_lojix::schema::lib::Input as MetaInput;
pub use meta_signal_lojix::schema::lib::Output as MetaOutput;
pub use lojix::schema::sema::SemaReadInput as SemaReadInput;
pub use lojix::schema::sema::SemaReadOutput as SemaReadOutput;
pub use lojix::schema::sema::SemaWriteInput as SemaWriteInput;
pub use lojix::schema::sema::SemaWriteOutput as SemaWriteOutput;
pub use signal_lojix::schema::lib::ClusterName as ClusterName;
pub use signal_lojix::schema::lib::NodeName as NodeName;
pub use signal_lojix::schema::lib::ClosurePath as ClosurePath;
pub use signal_lojix::schema::lib::FlakeReference as FlakeReference;
pub use signal_lojix::schema::lib::ProposalSource as ProposalSource;
pub use signal_lojix::schema::lib::GenerationIdentifier as GenerationIdentifier;
pub use signal_lojix::schema::lib::DeploymentIdentifier as DeploymentIdentifier;
pub use signal_lojix::schema::lib::GenerationSlot as GenerationSlot;
pub use signal_lojix::schema::lib::ActivationKind as ActivationKind;
pub use signal_lojix::schema::lib::DeploymentKind as DeploymentKind;

#[cfg(feature = "nota-text")]
pub use nota_next::{
    NotaDecode, NotaDecodeError, NotaEncode, NotaSource,
};

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalInput {
    OrdinaryInput(OrdinaryInput),
    MetaInput(MetaInput),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalOutput {
    OrdinaryOutput(OrdinaryOutput),
    MetaOutput(MetaOutput),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BuilderNode(pub NodeName);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum BuildTarget {
    Local,
    Remote(BuilderNode),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExtraSubstituter {
    pub url: String,
    pub public_key: String,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FlakeAuthRequest {
    pub source: ProposalSource,
    pub flake: FlakeReference,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ResolvedFlake {
    pub flake: FlakeReference,
    pub revision: String,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NixEvalCommand {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub deployment_kind: DeploymentKind,
    pub flake: FlakeReference,
    pub attribute: String,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NixBuildCommand {
    pub generation_identifier: GenerationIdentifier,
    pub closure_path: ClosurePath,
    pub target: BuildTarget,
    pub substituters: Vec<ExtraSubstituter>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CopyClosureCommand {
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub closure_path: ClosurePath,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivateGenerationCommand {
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub activation_kind: ActivationKind,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PathInfoGcCommand {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectCommand {
    ResolveFlakeAuth(FlakeAuthRequest),
    NixEval(NixEvalCommand),
    NixBuild(NixBuildCommand),
    CopyClosure(CopyClosureCommand),
    ActivateGeneration(ActivateGenerationCommand),
    PathInfoGc(PathInfoGcCommand),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EvaluatedClosure {
    pub generation_identifier: GenerationIdentifier,
    pub closure_path: ClosurePath,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BuiltClosure {
    pub generation_identifier: GenerationIdentifier,
    pub closure_path: ClosurePath,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CopiedClosure {
    pub generation_identifier: GenerationIdentifier,
    pub node_name: NodeName,
    pub closure_path: ClosurePath,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivatedGeneration {
    pub generation_identifier: GenerationIdentifier,
    pub node_name: NodeName,
    pub generation_slot: GenerationSlot,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GarbageCollected {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub reclaimed_paths: Integer,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EffectFailure {
    pub stage: EffectStage,
    pub detail: String,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectStage {
    FlakeAuth,
    Eval,
    Build,
    CopyClosure,
    Activate,
    Gc,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectResult {
    FlakeResolved(ResolvedFlake),
    ClosureEvaluated(EvaluatedClosure),
    ClosureBuilt(BuiltClosure),
    ClosureCopied(CopiedClosure),
    GenerationActivated(ActivatedGeneration),
    PathsCollected(GarbageCollected),
    EffectFailed(EffectFailure),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalInput),
    SemaReadCompleted(SemaReadOutput),
    SemaWriteCompleted(SemaWriteOutput),
    EffectCompleted(EffectResult),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    CommandSemaRead(SemaReadInput),
    CommandSemaWrite(SemaWriteInput),
    CommandEffect(EffectCommand),
    ReplyToSignal(SignalOutput),
    Continue(NexusWork),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    NexusWork(NexusWork),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    NexusAction(NexusAction),
}

impl BuilderNode {
    pub fn new(payload: NodeName) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &NodeName {
        &self.0
    }

    pub fn into_payload(self) -> NodeName {
        self.0
    }
}

impl From<NodeName> for BuilderNode {
    fn from(payload: NodeName) -> Self {
        Self::new(payload)
    }
}

impl SignalInput {
    pub fn ordinary_input(payload: OrdinaryInput) -> Self {
        Self::OrdinaryInput(payload)
    }

    pub fn meta_input(payload: MetaInput) -> Self {
        Self::MetaInput(payload)
    }
}

impl SignalOutput {
    pub fn ordinary_output(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryOutput(payload)
    }

    pub fn meta_output(payload: MetaOutput) -> Self {
        Self::MetaOutput(payload)
    }
}

impl BuildTarget {
    pub fn remote(payload: NodeName) -> Self {
        Self::Remote(BuilderNode::new(payload))
    }
}

impl EffectCommand {
    pub fn resolve_flake_auth(payload: FlakeAuthRequest) -> Self {
        Self::ResolveFlakeAuth(payload)
    }

    pub fn nix_eval(payload: NixEvalCommand) -> Self {
        Self::NixEval(payload)
    }

    pub fn nix_build(payload: NixBuildCommand) -> Self {
        Self::NixBuild(payload)
    }

    pub fn copy_closure(payload: CopyClosureCommand) -> Self {
        Self::CopyClosure(payload)
    }

    pub fn activate_generation(payload: ActivateGenerationCommand) -> Self {
        Self::ActivateGeneration(payload)
    }

    pub fn path_info_gc(payload: PathInfoGcCommand) -> Self {
        Self::PathInfoGc(payload)
    }
}

impl EffectResult {
    pub fn flake_resolved(payload: ResolvedFlake) -> Self {
        Self::FlakeResolved(payload)
    }

    pub fn closure_evaluated(payload: EvaluatedClosure) -> Self {
        Self::ClosureEvaluated(payload)
    }

    pub fn closure_built(payload: BuiltClosure) -> Self {
        Self::ClosureBuilt(payload)
    }

    pub fn closure_copied(payload: CopiedClosure) -> Self {
        Self::ClosureCopied(payload)
    }

    pub fn generation_activated(payload: ActivatedGeneration) -> Self {
        Self::GenerationActivated(payload)
    }

    pub fn paths_collected(payload: GarbageCollected) -> Self {
        Self::PathsCollected(payload)
    }

    pub fn effect_failed(payload: EffectFailure) -> Self {
        Self::EffectFailed(payload)
    }
}

impl NexusWork {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(payload)
    }

    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }

    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }

    pub fn effect_completed(payload: EffectResult) -> Self {
        Self::EffectCompleted(payload)
    }
}

impl NexusAction {
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }

    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(payload)
    }

    pub fn command_effect(payload: EffectCommand) -> Self {
        Self::CommandEffect(payload)
    }

    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(payload)
    }

    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(payload)
    }
}

impl Input {
    pub fn nexus_work(payload: NexusWork) -> Self {
        Self::NexusWork(payload)
    }
}

impl Output {
    pub fn nexus_action(payload: NexusAction) -> Self {
        Self::NexusAction(payload)
    }
}

impl From<OrdinaryInput> for SignalInput {
    fn from(payload: OrdinaryInput) -> Self {
        Self::OrdinaryInput(payload)
    }
}

impl From<MetaInput> for SignalInput {
    fn from(payload: MetaInput) -> Self {
        Self::MetaInput(payload)
    }
}

impl From<OrdinaryOutput> for SignalOutput {
    fn from(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryOutput(payload)
    }
}

impl From<MetaOutput> for SignalOutput {
    fn from(payload: MetaOutput) -> Self {
        Self::MetaOutput(payload)
    }
}

impl From<BuilderNode> for BuildTarget {
    fn from(payload: BuilderNode) -> Self {
        Self::Remote(payload)
    }
}

impl From<FlakeAuthRequest> for EffectCommand {
    fn from(payload: FlakeAuthRequest) -> Self {
        Self::ResolveFlakeAuth(payload)
    }
}

impl From<NixEvalCommand> for EffectCommand {
    fn from(payload: NixEvalCommand) -> Self {
        Self::NixEval(payload)
    }
}

impl From<NixBuildCommand> for EffectCommand {
    fn from(payload: NixBuildCommand) -> Self {
        Self::NixBuild(payload)
    }
}

impl From<CopyClosureCommand> for EffectCommand {
    fn from(payload: CopyClosureCommand) -> Self {
        Self::CopyClosure(payload)
    }
}

impl From<ActivateGenerationCommand> for EffectCommand {
    fn from(payload: ActivateGenerationCommand) -> Self {
        Self::ActivateGeneration(payload)
    }
}

impl From<PathInfoGcCommand> for EffectCommand {
    fn from(payload: PathInfoGcCommand) -> Self {
        Self::PathInfoGc(payload)
    }
}

impl From<ResolvedFlake> for EffectResult {
    fn from(payload: ResolvedFlake) -> Self {
        Self::FlakeResolved(payload)
    }
}

impl From<EvaluatedClosure> for EffectResult {
    fn from(payload: EvaluatedClosure) -> Self {
        Self::ClosureEvaluated(payload)
    }
}

impl From<BuiltClosure> for EffectResult {
    fn from(payload: BuiltClosure) -> Self {
        Self::ClosureBuilt(payload)
    }
}

impl From<CopiedClosure> for EffectResult {
    fn from(payload: CopiedClosure) -> Self {
        Self::ClosureCopied(payload)
    }
}

impl From<ActivatedGeneration> for EffectResult {
    fn from(payload: ActivatedGeneration) -> Self {
        Self::GenerationActivated(payload)
    }
}

impl From<GarbageCollected> for EffectResult {
    fn from(payload: GarbageCollected) -> Self {
        Self::PathsCollected(payload)
    }
}

impl From<EffectFailure> for EffectResult {
    fn from(payload: EffectFailure) -> Self {
        Self::EffectFailed(payload)
    }
}

impl From<SignalInput> for NexusWork {
    fn from(payload: SignalInput) -> Self {
        Self::SignalArrived(payload)
    }
}

impl From<SemaReadOutput> for NexusWork {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

impl From<SemaWriteOutput> for NexusWork {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

impl From<EffectResult> for NexusWork {
    fn from(payload: EffectResult) -> Self {
        Self::EffectCompleted(payload)
    }
}

impl From<SemaReadInput> for NexusAction {
    fn from(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }
}

impl From<SemaWriteInput> for NexusAction {
    fn from(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

impl From<EffectCommand> for NexusAction {
    fn from(payload: EffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
}

impl From<SignalOutput> for NexusAction {
    fn from(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(payload)
    }
}

impl From<NexusWork> for NexusAction {
    fn from(payload: NexusWork) -> Self {
        Self::Continue(payload)
    }
}

impl From<NexusWork> for Input {
    fn from(payload: NexusWork) -> Self {
        Self::NexusWork(payload)
    }
}

impl From<NexusAction> for Output {
    fn from(payload: NexusAction) -> Self {
        Self::NexusAction(payload)
    }
}

#[cfg(feature = "nota-text")]
impl SignalInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SignalOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl BuilderNode {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl BuildTarget {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ExtraSubstituter {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl FlakeAuthRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ResolvedFlake {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NixEvalCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NixBuildCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CopyClosureCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ActivateGenerationCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PathInfoGcCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl EffectCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl EvaluatedClosure {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl BuiltClosure {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CopiedClosure {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ActivatedGeneration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl GarbageCollected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl EffectFailure {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl EffectStage {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl EffectResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusWork {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusAction {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_NEXUS_WORK: u64 = 0x0000000000000000;
    pub const OUTPUT_NEXUS_ACTION: u64 = 0x0100000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputRoute {
    NexusWork,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum OutputRoute {
    NexusAction,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::NexusWork(_) => InputRoute::NexusWork,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::NexusWork(_) => short_header::INPUT_NEXUS_WORK,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_NEXUS_WORK => Ok(InputRoute::NexusWork),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::NexusAction(_) => OutputRoute::NexusAction,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::NexusAction(_) => short_header::OUTPUT_NEXUS_ACTION,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_NEXUS_ACTION => Ok(OutputRoute::NexusAction),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaReadCompleted,
    SemaWriteCompleted,
    EffectCompleted,
}

impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusActionRoute {
    CommandSemaRead,
    CommandSemaWrite,
    CommandEffect,
    ReplyToSignal,
    Continue,
}

impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}

impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => match route {
                NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
            },
            Self::Action(route) => match route {
                NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                NexusActionRoute::Continue => "NexusActionContinue",
            },
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct TraceEvent(pub ObjectName);

impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}

impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }

    pub fn object_name(&self) -> ObjectName {
        self.0
    }

    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginRoute(pub Integer);
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

impl triad_runtime::NexusWork for NexusWork {}

impl triad_runtime::NexusEffectCommand for EffectCommand {}

impl triad_runtime::NexusEffectResult for EffectResult {}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}

impl std::fmt::Display for ActorStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => write!(formatter, "actor resource busy: {message}"),
            Self::ConfigurationInvalid(message) => write!(formatter, "actor configuration invalid: {message}"),
        }
    }
}

impl std::error::Error for ActorStartFailure {}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}

impl std::fmt::Display for ActorStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => write!(formatter, "actor resource locked: {message}"),
            Self::ChildStillRunning(message) => write!(formatter, "actor child still running: {message}"),
        }
    }
}

impl std::error::Error for ActorStopFailure {}

pub type NexusRunnerNextStep = triad_runtime::NextStep<SignalOutput, SemaWriteInput, SemaReadInput, EffectCommand, NexusWork>;

impl triad_runtime::NexusAction for NexusAction {
    type Reply = SignalOutput;
    type SemaWrite = SemaWriteInput;
    type SemaRead = SemaReadInput;
    type Effect = EffectCommand;
    type Work = NexusWork;

    fn into_next_step(self) -> NexusRunnerNextStep {
        match self {
            Self::CommandSemaWrite(input) => triad_runtime::NextStep::SemaWrite(input),
            Self::CommandSemaRead(input) => triad_runtime::NextStep::SemaRead(input),
            Self::ReplyToSignal(output) => triad_runtime::NextStep::Reply(output),
            Self::CommandEffect(effect) => triad_runtime::NextStep::RunEffect(effect),
            Self::Continue(work) => triad_runtime::NextStep::Continue(work),
        }
    }
}

pub trait NexusEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }

    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }

    fn continuation_limit(&self) -> triad_runtime::ContinuationLimit {
        triad_runtime::ContinuationLimit::default()
    }

    fn apply_sema_write(&mut self, origin_route: OriginRoute, input: SemaWriteInput) -> SemaWriteOutput;
    fn observe_sema_read(&self, origin_route: OriginRoute, input: SemaReadInput) -> SemaReadOutput;
    fn run_effect(&mut self, input: EffectCommand) -> EffectResult;
    fn budget_exhausted_reply(&self, exhausted: triad_runtime::ContinuationExhausted) -> SignalOutput;

    fn decide(&mut self, input: nexus::Nexus<nexus::Work>) -> nexus::Nexus<nexus::Action>;

    fn execute(&mut self, input: nexus::Nexus<nexus::Work>) -> nexus::Nexus<nexus::Action>
    where
        Self: Sized,
    {
        self.trace_nexus_entered();
        let origin_route = input.origin_route();
        let first_work = input.into_root();
        let runner = triad_runtime::Runner::new(self.continuation_limit());
        let mut runner_adapter = NexusRunnerAdapter::new(self, origin_route);
        let reply = runner.drive(&mut runner_adapter, first_work);
        let output = NexusAction::reply_to_signal(reply).with_origin_route(origin_route);
        self.trace_nexus_decided();
        output
    }
}

struct NexusRunnerAdapter<'engine, Engine> {
    engine: &'engine mut Engine,
    origin_route: OriginRoute,
}

impl<'engine, Engine> NexusRunnerAdapter<'engine, Engine> {
    fn new(engine: &'engine mut Engine, origin_route: OriginRoute) -> Self {
        Self { engine, origin_route }
    }
}

impl<'engine, Engine> triad_runtime::RunnerEngines for NexusRunnerAdapter<'engine, Engine>
where
    Engine: NexusEngine,
{
    type Reply = SignalOutput;
    type SemaWrite = SemaWriteInput;
    type SemaRead = SemaReadInput;
    type Effect = EffectCommand;
    type Work = NexusWork;

    fn decide_next_step(&mut self, work: Self::Work) -> triad_runtime::runner::RunnerNextStep<Self> {
        let action = NexusEngine::decide(self.engine, work.with_origin_route(self.origin_route)).into_root();
        triad_runtime::NexusAction::into_next_step(action)
    }

    fn apply_sema_write(&mut self, write: Self::SemaWrite) -> Self::Work {
        let output: SemaWriteOutput = NexusEngine::apply_sema_write(self.engine, self.origin_route, write);
        NexusWork::sema_write_completed(output)
    }

    fn observe_sema_read(&self, read: Self::SemaRead) -> Self::Work {
        let output: SemaReadOutput = NexusEngine::observe_sema_read(self.engine, self.origin_route, read);
        NexusWork::sema_read_completed(output)
    }

    fn run_effect(&mut self, effect: Self::Effect) -> Self::Work {
        let output: EffectResult = NexusEngine::run_effect(self.engine, effect);
        NexusWork::effect_completed(output)
    }

    fn budget_exhausted_reply(&self, exhausted: triad_runtime::ContinuationExhausted) -> Self::Reply {
        NexusEngine::budget_exhausted_reply(self.engine, exhausted)
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
