// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use signal_lojix::schema::lib::Selection as Selection;
pub use signal_lojix::schema::lib::GenerationListing as GenerationListing;
pub use signal_lojix::schema::lib::Generation as Generation;
pub use signal_lojix::schema::lib::KeyMaterialQuery as KeyMaterialQuery;
pub use signal_lojix::schema::lib::KeyMaterialReport as KeyMaterialReport;
pub use signal_lojix::schema::lib::EventLogRange as EventLogRange;
pub use signal_lojix::schema::lib::EventLogPosition as EventLogPosition;
pub use signal_lojix::schema::lib::DeploymentPhaseEvent as DeploymentPhaseEvent;
pub use signal_lojix::schema::lib::CacheRetentionTransitionEvent as CacheRetentionTransitionEvent;
pub use signal_lojix::schema::lib::ClusterName as ClusterName;
pub use signal_lojix::schema::lib::NodeName as NodeName;
pub use signal_lojix::schema::lib::PinLabel as PinLabel;
pub use signal_lojix::schema::lib::ClosurePath as ClosurePath;
pub use signal_lojix::schema::lib::DeploymentIdentifier as DeploymentIdentifier;
pub use signal_lojix::schema::lib::GenerationIdentifier as GenerationIdentifier;
pub use signal_lojix::schema::lib::DeploymentKind as DeploymentKind;
pub use signal_lojix::schema::lib::ActivationKind as ActivationKind;
pub use signal_lojix::schema::lib::GenerationSlot as GenerationSlot;
pub use meta_signal_lojix::schema::lib::SystemDeployment as SystemDeployment;
pub use meta_signal_lojix::schema::lib::HomeDeployment as HomeDeployment;
pub use meta_signal_lojix::schema::lib::PinRequest as PinRequest;
pub use meta_signal_lojix::schema::lib::UnpinRequest as UnpinRequest;
pub use meta_signal_lojix::schema::lib::RetireRequest as RetireRequest;
pub use meta_signal_lojix::schema::lib::AcceptedDeploy as AcceptedDeploy;
pub use meta_signal_lojix::schema::lib::AppliedPin as AppliedPin;
pub use meta_signal_lojix::schema::lib::AppliedUnpin as AppliedUnpin;
pub use meta_signal_lojix::schema::lib::AppliedRetire as AppliedRetire;

#[cfg(feature = "nota-text")]
pub use nota_next::{
    NotaDecode, NotaDecodeError, NotaEncode, NotaSource,
};

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadInput {
    QueryGenerations(Selection),
    ReadEventLog(EventLogRange),
    CheckKeyMaterial(KeyMaterialQuery),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadOutput {
    GenerationsQueried(GenerationListing),
    EventLogRead(EventLogPage),
    KeyMaterialChecked(KeyMaterialReport),
    ReadMissed(RejectionReport),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogPage {
    pub deployment_events: Vec<DeploymentPhaseEvent>,
    pub retention_events: Vec<CacheRetentionTransitionEvent>,
    pub state_marker: StateMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteInput {
    RecordDeploySubmitted(DeploySubmission),
    RecordPhaseTransition(DeploymentPhaseEvent),
    RecordGenerationActivated(ActivationCommit),
    PinGeneration(PinRequest),
    UnpinGeneration(UnpinRequest),
    RetireGeneration(RetireRequest),
    RecordContainerTransition(ContainerTransition),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeploySubmission {
    System(SystemDeployment),
    Home(HomeDeployment),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivationCommit {
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_slot: GenerationSlot,
    pub closure_path: ClosurePath,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerTransition {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub container: ContainerName,
    pub state: ContainerState,
}

pub type ContainerName = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ContainerState {
    Starting,
    Started,
    Stopping,
    Stopped,
    Failed,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteOutput {
    DeploySubmitted(AcceptedDeploy),
    PhaseRecorded(PhaseReceipt),
    GenerationActivated(AppliedActivation),
    GenerationPinned(AppliedPin),
    GenerationUnpinned(AppliedUnpin),
    GenerationRetired(AppliedRetire),
    ContainerRecorded(ContainerReceipt),
    WriteRejected(RejectionReport),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PhaseReceipt {
    pub event_log_position: EventLogPosition,
    pub state_marker: StateMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedActivation {
    pub generation_identifier: GenerationIdentifier,
    pub generation_slot: GenerationSlot,
    pub state_marker: StateMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerReceipt {
    pub event_log_position: EventLogPosition,
    pub state_marker: StateMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionReport {
    pub reason: RejectionReason,
    pub marker: StateMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RejectionReason {
    GenerationUnknown,
    NodeUnknown,
    ClusterUnknown,
    PlanNotApproved,
    PinLabelInUse,
    PinLabelUnknown,
    GenerationActive,
    GenerationPinned,
    EventLogPositionOutOfRange,
    ProposalSourceUnreachable,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

pub type CommitSequence = Integer;

pub type StateDigest = Integer;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LiveSetTable(pub Vec<LiveGeneration>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LiveGeneration {
    pub deployment_identifier: DeploymentIdentifier,
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub deployment_kind: DeploymentKind,
    pub activation_kind: ActivationKind,
    pub generation_slot: GenerationSlot,
    pub closure_path: ClosurePath,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GcRootsTable(pub Vec<GcRoot>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GcRoot {
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_slot: GenerationSlot,
    pub closure_path: ClosurePath,
    pub label: Option<PinLabel>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogTable(pub Vec<EventLogEntry>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogEntry {
    pub event_log_position: EventLogPosition,
    pub record: LoggedEvent,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum LoggedEvent {
    Deployment(DeploymentPhaseEvent),
    CacheRetention(CacheRetentionTransitionEvent),
    Container(ContainerLifecycleRecord),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerLifecycleTable(pub Vec<ContainerLifecycleRecord>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerLifecycleRecord {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub container: ContainerName,
    pub state: ContainerState,
    pub event_log_position: EventLogPosition,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SemaReadInput(SemaReadInput),
    SemaWriteInput(SemaWriteInput),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SemaReadOutput(SemaReadOutput),
    SemaWriteOutput(SemaWriteOutput),
}

impl LiveSetTable {
    pub fn new(payload: Vec<LiveGeneration>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<LiveGeneration> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<LiveGeneration> {
        self.0
    }
}

impl From<Vec<LiveGeneration>> for LiveSetTable {
    fn from(payload: Vec<LiveGeneration>) -> Self {
        Self::new(payload)
    }
}

impl GcRootsTable {
    pub fn new(payload: Vec<GcRoot>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<GcRoot> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<GcRoot> {
        self.0
    }
}

impl From<Vec<GcRoot>> for GcRootsTable {
    fn from(payload: Vec<GcRoot>) -> Self {
        Self::new(payload)
    }
}

impl EventLogTable {
    pub fn new(payload: Vec<EventLogEntry>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<EventLogEntry> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<EventLogEntry> {
        self.0
    }
}

impl From<Vec<EventLogEntry>> for EventLogTable {
    fn from(payload: Vec<EventLogEntry>) -> Self {
        Self::new(payload)
    }
}

impl ContainerLifecycleTable {
    pub fn new(payload: Vec<ContainerLifecycleRecord>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<ContainerLifecycleRecord> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<ContainerLifecycleRecord> {
        self.0
    }
}

impl From<Vec<ContainerLifecycleRecord>> for ContainerLifecycleTable {
    fn from(payload: Vec<ContainerLifecycleRecord>) -> Self {
        Self::new(payload)
    }
}

impl SemaReadInput {
    pub fn query_generations(payload: Selection) -> Self {
        Self::QueryGenerations(payload)
    }

    pub fn read_event_log(payload: EventLogRange) -> Self {
        Self::ReadEventLog(payload)
    }

    pub fn check_key_material(payload: KeyMaterialQuery) -> Self {
        Self::CheckKeyMaterial(payload)
    }
}

impl SemaReadOutput {
    pub fn generations_queried(payload: GenerationListing) -> Self {
        Self::GenerationsQueried(payload)
    }

    pub fn event_log_read(payload: EventLogPage) -> Self {
        Self::EventLogRead(payload)
    }

    pub fn key_material_checked(payload: KeyMaterialReport) -> Self {
        Self::KeyMaterialChecked(payload)
    }

    pub fn read_missed(payload: RejectionReport) -> Self {
        Self::ReadMissed(payload)
    }
}

impl SemaWriteInput {
    pub fn record_deploy_submitted(payload: DeploySubmission) -> Self {
        Self::RecordDeploySubmitted(payload)
    }

    pub fn record_phase_transition(payload: DeploymentPhaseEvent) -> Self {
        Self::RecordPhaseTransition(payload)
    }

    pub fn record_generation_activated(payload: ActivationCommit) -> Self {
        Self::RecordGenerationActivated(payload)
    }

    pub fn pin_generation(payload: PinRequest) -> Self {
        Self::PinGeneration(payload)
    }

    pub fn unpin_generation(payload: UnpinRequest) -> Self {
        Self::UnpinGeneration(payload)
    }

    pub fn retire_generation(payload: RetireRequest) -> Self {
        Self::RetireGeneration(payload)
    }

    pub fn record_container_transition(payload: ContainerTransition) -> Self {
        Self::RecordContainerTransition(payload)
    }
}

impl DeploySubmission {
    pub fn system(payload: SystemDeployment) -> Self {
        Self::System(payload)
    }

    pub fn home(payload: HomeDeployment) -> Self {
        Self::Home(payload)
    }
}

impl SemaWriteOutput {
    pub fn deploy_submitted(payload: AcceptedDeploy) -> Self {
        Self::DeploySubmitted(payload)
    }

    pub fn phase_recorded(payload: PhaseReceipt) -> Self {
        Self::PhaseRecorded(payload)
    }

    pub fn generation_activated(payload: AppliedActivation) -> Self {
        Self::GenerationActivated(payload)
    }

    pub fn generation_pinned(payload: AppliedPin) -> Self {
        Self::GenerationPinned(payload)
    }

    pub fn generation_unpinned(payload: AppliedUnpin) -> Self {
        Self::GenerationUnpinned(payload)
    }

    pub fn generation_retired(payload: AppliedRetire) -> Self {
        Self::GenerationRetired(payload)
    }

    pub fn container_recorded(payload: ContainerReceipt) -> Self {
        Self::ContainerRecorded(payload)
    }

    pub fn write_rejected(payload: RejectionReport) -> Self {
        Self::WriteRejected(payload)
    }
}

impl LoggedEvent {
    pub fn deployment(payload: DeploymentPhaseEvent) -> Self {
        Self::Deployment(payload)
    }

    pub fn cache_retention(payload: CacheRetentionTransitionEvent) -> Self {
        Self::CacheRetention(payload)
    }

    pub fn container(payload: ContainerLifecycleRecord) -> Self {
        Self::Container(payload)
    }
}

impl Input {
    pub fn sema_read_input(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }

    pub fn sema_write_input(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

impl Output {
    pub fn sema_read_output(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }

    pub fn sema_write_output(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

impl From<Selection> for SemaReadInput {
    fn from(payload: Selection) -> Self {
        Self::QueryGenerations(payload)
    }
}

impl From<EventLogRange> for SemaReadInput {
    fn from(payload: EventLogRange) -> Self {
        Self::ReadEventLog(payload)
    }
}

impl From<KeyMaterialQuery> for SemaReadInput {
    fn from(payload: KeyMaterialQuery) -> Self {
        Self::CheckKeyMaterial(payload)
    }
}

impl From<GenerationListing> for SemaReadOutput {
    fn from(payload: GenerationListing) -> Self {
        Self::GenerationsQueried(payload)
    }
}

impl From<EventLogPage> for SemaReadOutput {
    fn from(payload: EventLogPage) -> Self {
        Self::EventLogRead(payload)
    }
}

impl From<KeyMaterialReport> for SemaReadOutput {
    fn from(payload: KeyMaterialReport) -> Self {
        Self::KeyMaterialChecked(payload)
    }
}

impl From<RejectionReport> for SemaReadOutput {
    fn from(payload: RejectionReport) -> Self {
        Self::ReadMissed(payload)
    }
}

impl From<DeploySubmission> for SemaWriteInput {
    fn from(payload: DeploySubmission) -> Self {
        Self::RecordDeploySubmitted(payload)
    }
}

impl From<DeploymentPhaseEvent> for SemaWriteInput {
    fn from(payload: DeploymentPhaseEvent) -> Self {
        Self::RecordPhaseTransition(payload)
    }
}

impl From<ActivationCommit> for SemaWriteInput {
    fn from(payload: ActivationCommit) -> Self {
        Self::RecordGenerationActivated(payload)
    }
}

impl From<PinRequest> for SemaWriteInput {
    fn from(payload: PinRequest) -> Self {
        Self::PinGeneration(payload)
    }
}

impl From<UnpinRequest> for SemaWriteInput {
    fn from(payload: UnpinRequest) -> Self {
        Self::UnpinGeneration(payload)
    }
}

impl From<RetireRequest> for SemaWriteInput {
    fn from(payload: RetireRequest) -> Self {
        Self::RetireGeneration(payload)
    }
}

impl From<ContainerTransition> for SemaWriteInput {
    fn from(payload: ContainerTransition) -> Self {
        Self::RecordContainerTransition(payload)
    }
}

impl From<SystemDeployment> for DeploySubmission {
    fn from(payload: SystemDeployment) -> Self {
        Self::System(payload)
    }
}

impl From<HomeDeployment> for DeploySubmission {
    fn from(payload: HomeDeployment) -> Self {
        Self::Home(payload)
    }
}

impl From<AcceptedDeploy> for SemaWriteOutput {
    fn from(payload: AcceptedDeploy) -> Self {
        Self::DeploySubmitted(payload)
    }
}

impl From<PhaseReceipt> for SemaWriteOutput {
    fn from(payload: PhaseReceipt) -> Self {
        Self::PhaseRecorded(payload)
    }
}

impl From<AppliedActivation> for SemaWriteOutput {
    fn from(payload: AppliedActivation) -> Self {
        Self::GenerationActivated(payload)
    }
}

impl From<AppliedPin> for SemaWriteOutput {
    fn from(payload: AppliedPin) -> Self {
        Self::GenerationPinned(payload)
    }
}

impl From<AppliedUnpin> for SemaWriteOutput {
    fn from(payload: AppliedUnpin) -> Self {
        Self::GenerationUnpinned(payload)
    }
}

impl From<AppliedRetire> for SemaWriteOutput {
    fn from(payload: AppliedRetire) -> Self {
        Self::GenerationRetired(payload)
    }
}

impl From<ContainerReceipt> for SemaWriteOutput {
    fn from(payload: ContainerReceipt) -> Self {
        Self::ContainerRecorded(payload)
    }
}

impl From<RejectionReport> for SemaWriteOutput {
    fn from(payload: RejectionReport) -> Self {
        Self::WriteRejected(payload)
    }
}

impl From<DeploymentPhaseEvent> for LoggedEvent {
    fn from(payload: DeploymentPhaseEvent) -> Self {
        Self::Deployment(payload)
    }
}

impl From<CacheRetentionTransitionEvent> for LoggedEvent {
    fn from(payload: CacheRetentionTransitionEvent) -> Self {
        Self::CacheRetention(payload)
    }
}

impl From<ContainerLifecycleRecord> for LoggedEvent {
    fn from(payload: ContainerLifecycleRecord) -> Self {
        Self::Container(payload)
    }
}

impl From<SemaReadInput> for Input {
    fn from(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }
}

impl From<SemaWriteInput> for Input {
    fn from(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

impl From<SemaReadOutput> for Output {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }
}

impl From<SemaWriteOutput> for Output {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

#[cfg(feature = "nota-text")]
impl SemaReadInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaReadOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl EventLogPage {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaWriteInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DeploySubmission {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ActivationCommit {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ContainerTransition {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ContainerState {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaWriteOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PhaseReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl AppliedActivation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ContainerReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectionReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl StateMarker {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl LiveSetTable {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl LiveGeneration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl GcRootsTable {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl GcRoot {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl EventLogTable {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl EventLogEntry {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl LoggedEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ContainerLifecycleTable {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ContainerLifecycleRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_SEMA_READ_INPUT: u64 = 0x0000000000000000;
    pub const INPUT_SEMA_WRITE_INPUT: u64 = 0x0001000000000000;
    pub const OUTPUT_SEMA_READ_OUTPUT: u64 = 0x0100000000000000;
    pub const OUTPUT_SEMA_WRITE_OUTPUT: u64 = 0x0101000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputRoute {
    SemaReadInput,
    SemaWriteInput,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum OutputRoute {
    SemaReadOutput,
    SemaWriteOutput,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::SemaReadInput(_) => InputRoute::SemaReadInput,
            Self::SemaWriteInput(_) => InputRoute::SemaWriteInput,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::SemaReadInput(_) => short_header::INPUT_SEMA_READ_INPUT,
            Self::SemaWriteInput(_) => short_header::INPUT_SEMA_WRITE_INPUT,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_SEMA_READ_INPUT => Ok(InputRoute::SemaReadInput),
            short_header::INPUT_SEMA_WRITE_INPUT => Ok(InputRoute::SemaWriteInput),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::SemaReadOutput(_) => OutputRoute::SemaReadOutput,
            Self::SemaWriteOutput(_) => OutputRoute::SemaWriteOutput,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::SemaReadOutput(_) => short_header::OUTPUT_SEMA_READ_OUTPUT,
            Self::SemaWriteOutput(_) => short_header::OUTPUT_SEMA_WRITE_OUTPUT,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_SEMA_READ_OUTPUT => Ok(OutputRoute::SemaReadOutput),
            short_header::OUTPUT_SEMA_WRITE_OUTPUT => Ok(OutputRoute::SemaWriteOutput),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaReadInputRoute {
    QueryGenerations,
    ReadEventLog,
    CheckKeyMaterial,
}

impl SemaReadInput {
    pub fn route(&self) -> SemaReadInputRoute {
        match self {
            Self::QueryGenerations(_) => SemaReadInputRoute::QueryGenerations,
            Self::ReadEventLog(_) => SemaReadInputRoute::ReadEventLog,
            Self::CheckKeyMaterial(_) => SemaReadInputRoute::CheckKeyMaterial,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaReadOutputRoute {
    GenerationsQueried,
    EventLogRead,
    KeyMaterialChecked,
    ReadMissed,
}

impl SemaReadOutput {
    pub fn route(&self) -> SemaReadOutputRoute {
        match self {
            Self::GenerationsQueried(_) => SemaReadOutputRoute::GenerationsQueried,
            Self::EventLogRead(_) => SemaReadOutputRoute::EventLogRead,
            Self::KeyMaterialChecked(_) => SemaReadOutputRoute::KeyMaterialChecked,
            Self::ReadMissed(_) => SemaReadOutputRoute::ReadMissed,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaWriteInputRoute {
    RecordDeploySubmitted,
    RecordPhaseTransition,
    RecordGenerationActivated,
    PinGeneration,
    UnpinGeneration,
    RetireGeneration,
    RecordContainerTransition,
}

impl SemaWriteInput {
    pub fn route(&self) -> SemaWriteInputRoute {
        match self {
            Self::RecordDeploySubmitted(_) => SemaWriteInputRoute::RecordDeploySubmitted,
            Self::RecordPhaseTransition(_) => SemaWriteInputRoute::RecordPhaseTransition,
            Self::RecordGenerationActivated(_) => SemaWriteInputRoute::RecordGenerationActivated,
            Self::PinGeneration(_) => SemaWriteInputRoute::PinGeneration,
            Self::UnpinGeneration(_) => SemaWriteInputRoute::UnpinGeneration,
            Self::RetireGeneration(_) => SemaWriteInputRoute::RetireGeneration,
            Self::RecordContainerTransition(_) => SemaWriteInputRoute::RecordContainerTransition,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaWriteOutputRoute {
    DeploySubmitted,
    PhaseRecorded,
    GenerationActivated,
    GenerationPinned,
    GenerationUnpinned,
    GenerationRetired,
    ContainerRecorded,
    WriteRejected,
}

impl SemaWriteOutput {
    pub fn route(&self) -> SemaWriteOutputRoute {
        match self {
            Self::DeploySubmitted(_) => SemaWriteOutputRoute::DeploySubmitted,
            Self::PhaseRecorded(_) => SemaWriteOutputRoute::PhaseRecorded,
            Self::GenerationActivated(_) => SemaWriteOutputRoute::GenerationActivated,
            Self::GenerationPinned(_) => SemaWriteOutputRoute::GenerationPinned,
            Self::GenerationUnpinned(_) => SemaWriteOutputRoute::GenerationUnpinned,
            Self::GenerationRetired(_) => SemaWriteOutputRoute::GenerationRetired,
            Self::ContainerRecorded(_) => SemaWriteOutputRoute::ContainerRecorded,
            Self::WriteRejected(_) => SemaWriteOutputRoute::WriteRejected,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaObjectName {
    WriteInput(SemaWriteInputRoute),
    ReadInput(SemaReadInputRoute),
    WriteOutput(SemaWriteOutputRoute),
    ReadOutput(SemaReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}

impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => match route {
                SemaWriteInputRoute::RecordDeploySubmitted => "SemaWriteInputRecordDeploySubmitted",
                SemaWriteInputRoute::RecordPhaseTransition => "SemaWriteInputRecordPhaseTransition",
                SemaWriteInputRoute::RecordGenerationActivated => "SemaWriteInputRecordGenerationActivated",
                SemaWriteInputRoute::PinGeneration => "SemaWriteInputPinGeneration",
                SemaWriteInputRoute::UnpinGeneration => "SemaWriteInputUnpinGeneration",
                SemaWriteInputRoute::RetireGeneration => "SemaWriteInputRetireGeneration",
                SemaWriteInputRoute::RecordContainerTransition => "SemaWriteInputRecordContainerTransition",
            },
            Self::ReadInput(route) => match route {
                SemaReadInputRoute::QueryGenerations => "SemaReadInputQueryGenerations",
                SemaReadInputRoute::ReadEventLog => "SemaReadInputReadEventLog",
                SemaReadInputRoute::CheckKeyMaterial => "SemaReadInputCheckKeyMaterial",
            },
            Self::WriteOutput(route) => match route {
                SemaWriteOutputRoute::DeploySubmitted => "SemaWriteOutputDeploySubmitted",
                SemaWriteOutputRoute::PhaseRecorded => "SemaWriteOutputPhaseRecorded",
                SemaWriteOutputRoute::GenerationActivated => "SemaWriteOutputGenerationActivated",
                SemaWriteOutputRoute::GenerationPinned => "SemaWriteOutputGenerationPinned",
                SemaWriteOutputRoute::GenerationUnpinned => "SemaWriteOutputGenerationUnpinned",
                SemaWriteOutputRoute::GenerationRetired => "SemaWriteOutputGenerationRetired",
                SemaWriteOutputRoute::ContainerRecorded => "SemaWriteOutputContainerRecorded",
                SemaWriteOutputRoute::WriteRejected => "SemaWriteOutputWriteRejected",
            },
            Self::ReadOutput(route) => match route {
                SemaReadOutputRoute::GenerationsQueried => "SemaReadOutputGenerationsQueried",
                SemaReadOutputRoute::EventLogRead => "SemaReadOutputEventLogRead",
                SemaReadOutputRoute::KeyMaterialChecked => "SemaReadOutputKeyMaterialChecked",
                SemaReadOutputRoute::ReadMissed => "SemaReadOutputReadMissed",
            },
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObjectName {
    Sema(SemaObjectName),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct TraceEvent(pub ObjectName);

impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}

impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }

    pub fn object_name(&self) -> ObjectName {
        self.0
    }

    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginRoute(pub Integer);
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::SemaWriteInput;
    pub type WriteOutput = super::SemaWriteOutput;
    pub type ReadInput = super::SemaReadInput;
    pub type ReadOutput = super::SemaReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

impl SemaWriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaWriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl triad_runtime::SemaWriteInput for SemaWriteInput {}

impl triad_runtime::SemaWriteOutput for SemaWriteOutput {}

impl triad_runtime::SemaReadInput for SemaReadInput {}

impl triad_runtime::SemaReadOutput for SemaReadOutput {}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}

impl std::fmt::Display for ActorStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => write!(formatter, "actor resource busy: {message}"),
            Self::ConfigurationInvalid(message) => write!(formatter, "actor configuration invalid: {message}"),
        }
    }
}

impl std::error::Error for ActorStartFailure {}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}

impl std::fmt::Display for ActorStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => write!(formatter, "actor resource locked: {message}"),
            Self::ChildStillRunning(message) => write!(formatter, "actor child still running: {message}"),
        }
    }
}

impl std::error::Error for ActorStopFailure {}

pub trait SemaEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }

    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }

    fn apply_inner(&mut self, input: sema::Sema<sema::WriteInput>) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(&self, input: sema::Sema<sema::ReadInput>) -> sema::Sema<sema::ReadOutput>;

    fn apply(&mut self, input: sema::Sema<sema::WriteInput>) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }

    fn observe(&self, input: sema::Sema<sema::ReadInput>) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
