[package]
name = "lojix-client"
version = "8.1.0"
edition = "2024"
rust-version = "1.89"
publish = false

[[bin]]
name = "lojix"
path = "src/main.rs"

[dependencies]
lojix = { path = "../..", default-features = false }
datom-codec = { git = "https://github.com/LiGoldragon/datom-codec", rev = "4dff16b4f7412febc3b71aac8b49680cd20988cb" }
protos = { git = "https://github.com/LiGoldragon/protos", rev = "15b41da8f2579e73ead59bc0c2b97529b8ac32d3" }
signal-lojix = { git = "https://github.com/LiGoldragon/signal-lojix", rev = "cd164896311af9849e2ddf1cdbdd35b5feedcdd1", features = ["datom"] }
signal = { git = "https://github.com/LiGoldragon/signal", rev = "8f9a0deb701cebbea518679548df4a795affc918", default-features = false }

[lints.rust]
unsafe_code = "forbid"
