[package]
name = "lojix-client"
version = "4.0.1"
edition = "2024"
rust-version = "1.89"
publish = false

[[bin]]
name = "lojix"
path = "src/main.rs"

[dependencies]
lojix = { path = "../..", default-features = false }
datom-codec = { git = "https://github.com/LiGoldragon/datom-codec", rev = "627db67f2655efd9f786864009955005fd8ab2ad" }
protos = { git = "https://github.com/LiGoldragon/protos", rev = "171b21f65337983ab624b7b906397a4f1f92c5a3" }
signal-lojix = { git = "https://github.com/LiGoldragon/signal-lojix", rev = "5c94485c84d20d5b1496d867a2b40f2d908a02e3", features = ["datom"] }
signal = { git = "https://github.com/LiGoldragon/signal", rev = "8f9a0deb701cebbea518679548df4a795affc918", default-features = false }

[lints.rust]
unsafe_code = "forbid"
