[package]
name = "meta-lojix-client"
version = "7.0.0"
edition = "2024"
rust-version = "1.89"
publish = false

[[bin]]
name = "lojix-meta"
path = "src/main.rs"

[dependencies]
lojix = { path = "../..", default-features = false }
datom-codec = { git = "https://github.com/LiGoldragon/datom-codec", rev = "09e2a9d52bf7f2f11e51d15cb6c3177f72c6c927" }
protos = { git = "https://github.com/LiGoldragon/protos", rev = "1febca7836bf8d5f5973a302fdd50aa9c84c159b" }
meta-signal-lojix = { git = "https://github.com/LiGoldragon/meta-signal-lojix", rev = "b500561f0ce813917366997581412b7a79aebc99", features = ["datom"] }
signal-lojix = { git = "https://github.com/LiGoldragon/signal-lojix", rev = "f7866bf013499503d21491bcdaadaf88ea6c810c" }
signal = { git = "https://github.com/LiGoldragon/signal", rev = "8f9a0deb701cebbea518679548df4a795affc918", default-features = false }
horizon-lib = { git = "https://github.com/LiGoldragon/horizon-rs", rev = "ee8d6f8d27eb6e200504807971ffdd26aaca7ed1", package = "horizon-lib" }

[lints.rust]
unsafe_code = "forbid"

[dev-dependencies]
tempfile = "3"
