// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_lojix::schema::lib::Input as OrdinaryInput;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::Output as OrdinaryOutput;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::Input as MetaInput;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::Output as MetaOutput;
#[rustfmt::skip]
pub use crate::schema::sema::SemaReadInput as SemaReadInput;
#[rustfmt::skip]
pub use crate::schema::sema::SemaReadOutput as SemaReadOutput;
#[rustfmt::skip]
pub use crate::schema::sema::SemaWriteInput as SemaWriteInput;
#[rustfmt::skip]
pub use crate::schema::sema::SemaWriteOutput as SemaWriteOutput;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ClusterName as ClusterName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::NodeName as NodeName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ClosurePath as ClosurePath;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::FlakeReference as FlakeReference;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ProposalSource as ProposalSource;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::SourceRevisionPolicy as SourceRevisionPolicy;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::SourceRevisionRecord as SourceRevisionRecord;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::UserName as UserName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationIdentifier as GenerationIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentIdentifier as DeploymentIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationSlot as GenerationSlot;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ActivationEffect as ActivationEffect;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::HostDeployAction as HostDeployAction;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::HostComposition as HostComposition;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationArtifact as GenerationArtifact;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::UserEnvironmentAction as UserEnvironmentAction;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalInput {
    OrdinaryInput(OrdinaryInput),
    MetaInput(MetaInput),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SignalOutput {
    OrdinaryOutput(OrdinaryOutput),
    MetaOutput(MetaOutput),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BuilderNode(NodeName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TargetStore(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum BuildTarget {
    Local,
    Remote(BuilderNode),
    TargetStore(TargetStore),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExtraSubstituter {
    pub url: String,
    pub public_key: String,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FlakeAuthRequest {
    pub source: ProposalSource,
    pub flake: FlakeReference,
    pub source_revision_policy: SourceRevisionPolicy,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ResolvedFlake(SourceRevisionRecord);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UserEnvironmentMaterialization(UserName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MaterializationShape {
    CompleteHost,
    BaseHost,
    UserEnvironment(UserEnvironmentMaterialization),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HorizonMaterializationCommand {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub source: ProposalSource,
    pub shape: MaterializationShape,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FlakeInputReference {
    pub url: String,
    pub nix_archive_hash: String,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FlakeInputOverride {
    pub name: String,
    pub reference: FlakeInputReference,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MaterializedInputs(Vec<FlakeInputOverride>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NixEvalCommand {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_artifact: GenerationArtifact,
    pub flake: FlakeReference,
    pub source_revision: SourceRevisionRecord,
    pub attribute: String,
    pub overrides: Vec<FlakeInputOverride>,
    pub target: BuildTarget,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NixBuildCommand {
    pub generation_identifier: GenerationIdentifier,
    pub closure_path: ClosurePath,
    pub target: BuildTarget,
    pub substituters: Vec<ExtraSubstituter>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CopyClosureCommand {
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub closure_path: ClosurePath,
    pub source: BuildTarget,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UserEnvironmentActivationProfile {
    pub action: UserEnvironmentAction,
    pub user: UserName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ActivationProfile {
    Host(HostDeployAction),
    UserEnvironment(UserEnvironmentActivationProfile),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivateGenerationCommand {
    pub deployment_identifier: DeploymentIdentifier,
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub closure_path: ClosurePath,
    pub activation_effect: ActivationEffect,
    pub profile: ActivationProfile,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PathInfoGcCommand {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HermeticCheckCommand {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub flake: FlakeReference,
    pub system: String,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CheckBuilt {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub closure_path: ClosurePath,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BringUpTestVmCommand {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub host: NodeName,
    pub runner: ClosurePath,
    pub guest_ip: String,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TearDownTestVmCommand {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub host: NodeName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestVmBroughtUp {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub host: NodeName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestVmTornDown {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub host: NodeName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectCommand {
    ResolveFlakeAuth(FlakeAuthRequest),
    MaterializeHorizon(HorizonMaterializationCommand),
    NixEval(NixEvalCommand),
    NixBuild(NixBuildCommand),
    CopyClosure(CopyClosureCommand),
    ActivateGeneration(ActivateGenerationCommand),
    PathInfoGc(PathInfoGcCommand),
    HermeticCheck(HermeticCheckCommand),
    BringUpTestVm(BringUpTestVmCommand),
    TearDownTestVm(TearDownTestVmCommand),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EvaluatedClosure {
    pub generation_identifier: GenerationIdentifier,
    pub closure_path: ClosurePath,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BuiltClosure {
    pub generation_identifier: GenerationIdentifier,
    pub closure_path: ClosurePath,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CopiedClosure {
    pub generation_identifier: GenerationIdentifier,
    pub node_name: NodeName,
    pub closure_path: ClosurePath,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivatedGeneration {
    pub generation_identifier: GenerationIdentifier,
    pub node_name: NodeName,
    pub generation_slot: GenerationSlot,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GarbageCollected {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub reclaimed_paths: Integer,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EffectFailure {
    pub stage: EffectStage,
    pub detail: String,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum EffectStage {
    FlakeAuth,
    MaterializeHorizon,
    Eval,
    Build,
    CopyClosure,
    Activate,
    Gc,
    HermeticCheck,
    BringUpTestVm,
    TearDownTestVm,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectResult {
    FlakeResolved(ResolvedFlake),
    HorizonMaterialized(MaterializedInputs),
    ClosureEvaluated(EvaluatedClosure),
    ClosureBuilt(BuiltClosure),
    ClosureCopied(CopiedClosure),
    GenerationActivated(ActivatedGeneration),
    PathsCollected(GarbageCollected),
    HermeticCheckBuilt(CheckBuilt),
    TestVmBroughtUp(TestVmBroughtUp),
    TestVmTornDown(TestVmTornDown),
    EffectFailed(EffectFailure),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalInput),
    SemaReadCompleted(SemaReadOutput),
    SemaWriteCompleted(SemaWriteOutput),
    EffectCompleted(EffectResult),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    CommandSemaRead(SemaReadInput),
    CommandSemaWrite(SemaWriteInput),
    CommandEffect(EffectCommand),
    ReplyToSignal(SignalOutput),
    Continue(NexusWork),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    NexusWork(NexusWork),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    NexusAction(NexusAction),
}

#[rustfmt::skip]
impl BuilderNode {
    pub fn new(payload: NodeName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NodeName {
        &self.0
    }
    pub fn into_payload(self) -> NodeName {
        self.0
    }
}
#[rustfmt::skip]
impl From<NodeName> for BuilderNode {
    fn from(payload: NodeName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TargetStore {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TargetStore {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ResolvedFlake {
    pub fn new(payload: SourceRevisionRecord) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SourceRevisionRecord {
        &self.0
    }
    pub fn into_payload(self) -> SourceRevisionRecord {
        self.0
    }
}
#[rustfmt::skip]
impl From<SourceRevisionRecord> for ResolvedFlake {
    fn from(payload: SourceRevisionRecord) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UserEnvironmentMaterialization {
    pub fn new(payload: UserName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UserName {
        &self.0
    }
    pub fn into_payload(self) -> UserName {
        self.0
    }
}
#[rustfmt::skip]
impl From<UserName> for UserEnvironmentMaterialization {
    fn from(payload: UserName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MaterializedInputs {
    pub fn new(payload: Vec<FlakeInputOverride>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<FlakeInputOverride> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<FlakeInputOverride> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<FlakeInputOverride>> for MaterializedInputs {
    fn from(payload: Vec<FlakeInputOverride>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SignalInput {
    pub fn ordinary_input(payload: OrdinaryInput) -> Self {
        Self::OrdinaryInput(payload)
    }
    pub fn meta_input(payload: MetaInput) -> Self {
        Self::MetaInput(payload)
    }
}

#[rustfmt::skip]
impl SignalOutput {
    pub fn ordinary_output(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryOutput(payload)
    }
    pub fn meta_output(payload: MetaOutput) -> Self {
        Self::MetaOutput(payload)
    }
}

#[rustfmt::skip]
impl BuildTarget {
    pub fn remote(payload: NodeName) -> Self {
        Self::Remote(BuilderNode::new(payload))
    }
    pub fn target_store(payload: String) -> Self {
        Self::TargetStore(TargetStore::new(payload))
    }
}

#[rustfmt::skip]
impl MaterializationShape {
    pub fn user_environment(payload: UserName) -> Self {
        Self::UserEnvironment(UserEnvironmentMaterialization::new(payload))
    }
}

#[rustfmt::skip]
impl ActivationProfile {
    pub fn host(payload: HostDeployAction) -> Self {
        Self::Host(payload)
    }
    pub fn user_environment(payload: UserEnvironmentActivationProfile) -> Self {
        Self::UserEnvironment(payload)
    }
}

#[rustfmt::skip]
impl EffectCommand {
    pub fn resolve_flake_auth(payload: FlakeAuthRequest) -> Self {
        Self::ResolveFlakeAuth(payload)
    }
    pub fn materialize_horizon(payload: HorizonMaterializationCommand) -> Self {
        Self::MaterializeHorizon(payload)
    }
    pub fn nix_eval(payload: NixEvalCommand) -> Self {
        Self::NixEval(payload)
    }
    pub fn nix_build(payload: NixBuildCommand) -> Self {
        Self::NixBuild(payload)
    }
    pub fn copy_closure(payload: CopyClosureCommand) -> Self {
        Self::CopyClosure(payload)
    }
    pub fn activate_generation(payload: ActivateGenerationCommand) -> Self {
        Self::ActivateGeneration(payload)
    }
    pub fn path_info_gc(payload: PathInfoGcCommand) -> Self {
        Self::PathInfoGc(payload)
    }
    pub fn hermetic_check(payload: HermeticCheckCommand) -> Self {
        Self::HermeticCheck(payload)
    }
    pub fn bring_up_test_vm(payload: BringUpTestVmCommand) -> Self {
        Self::BringUpTestVm(payload)
    }
    pub fn tear_down_test_vm(payload: TearDownTestVmCommand) -> Self {
        Self::TearDownTestVm(payload)
    }
}

#[rustfmt::skip]
impl EffectResult {
    pub fn flake_resolved(payload: SourceRevisionRecord) -> Self {
        Self::FlakeResolved(ResolvedFlake::new(payload))
    }
    pub fn horizon_materialized(payload: Vec<FlakeInputOverride>) -> Self {
        Self::HorizonMaterialized(MaterializedInputs::new(payload))
    }
    pub fn closure_evaluated(payload: EvaluatedClosure) -> Self {
        Self::ClosureEvaluated(payload)
    }
    pub fn closure_built(payload: BuiltClosure) -> Self {
        Self::ClosureBuilt(payload)
    }
    pub fn closure_copied(payload: CopiedClosure) -> Self {
        Self::ClosureCopied(payload)
    }
    pub fn generation_activated(payload: ActivatedGeneration) -> Self {
        Self::GenerationActivated(payload)
    }
    pub fn paths_collected(payload: GarbageCollected) -> Self {
        Self::PathsCollected(payload)
    }
    pub fn hermetic_check_built(payload: CheckBuilt) -> Self {
        Self::HermeticCheckBuilt(payload)
    }
    pub fn test_vm_brought_up(payload: TestVmBroughtUp) -> Self {
        Self::TestVmBroughtUp(payload)
    }
    pub fn test_vm_torn_down(payload: TestVmTornDown) -> Self {
        Self::TestVmTornDown(payload)
    }
    pub fn effect_failed(payload: EffectFailure) -> Self {
        Self::EffectFailed(payload)
    }
}

#[rustfmt::skip]
impl NexusWork {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(payload)
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }
    pub fn effect_completed(payload: EffectResult) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_effect(payload: EffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(payload)
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn nexus_work(payload: NexusWork) -> Self {
        Self::NexusWork(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn nexus_action(payload: NexusAction) -> Self {
        Self::NexusAction(payload)
    }
}

#[rustfmt::skip]
impl From<OrdinaryInput> for SignalInput {
    fn from(payload: OrdinaryInput) -> Self {
        Self::OrdinaryInput(payload)
    }
}

#[rustfmt::skip]
impl From<MetaInput> for SignalInput {
    fn from(payload: MetaInput) -> Self {
        Self::MetaInput(payload)
    }
}

#[rustfmt::skip]
impl From<OrdinaryOutput> for SignalOutput {
    fn from(payload: OrdinaryOutput) -> Self {
        Self::OrdinaryOutput(payload)
    }
}

#[rustfmt::skip]
impl From<MetaOutput> for SignalOutput {
    fn from(payload: MetaOutput) -> Self {
        Self::MetaOutput(payload)
    }
}

#[rustfmt::skip]
impl From<BuilderNode> for BuildTarget {
    fn from(payload: BuilderNode) -> Self {
        Self::Remote(payload)
    }
}

#[rustfmt::skip]
impl From<TargetStore> for BuildTarget {
    fn from(payload: TargetStore) -> Self {
        Self::TargetStore(payload)
    }
}

#[rustfmt::skip]
impl From<UserEnvironmentMaterialization> for MaterializationShape {
    fn from(payload: UserEnvironmentMaterialization) -> Self {
        Self::UserEnvironment(payload)
    }
}

#[rustfmt::skip]
impl From<HostDeployAction> for ActivationProfile {
    fn from(payload: HostDeployAction) -> Self {
        Self::Host(payload)
    }
}

#[rustfmt::skip]
impl From<UserEnvironmentActivationProfile> for ActivationProfile {
    fn from(payload: UserEnvironmentActivationProfile) -> Self {
        Self::UserEnvironment(payload)
    }
}

#[rustfmt::skip]
impl From<FlakeAuthRequest> for EffectCommand {
    fn from(payload: FlakeAuthRequest) -> Self {
        Self::ResolveFlakeAuth(payload)
    }
}

#[rustfmt::skip]
impl From<HorizonMaterializationCommand> for EffectCommand {
    fn from(payload: HorizonMaterializationCommand) -> Self {
        Self::MaterializeHorizon(payload)
    }
}

#[rustfmt::skip]
impl From<NixEvalCommand> for EffectCommand {
    fn from(payload: NixEvalCommand) -> Self {
        Self::NixEval(payload)
    }
}

#[rustfmt::skip]
impl From<NixBuildCommand> for EffectCommand {
    fn from(payload: NixBuildCommand) -> Self {
        Self::NixBuild(payload)
    }
}

#[rustfmt::skip]
impl From<CopyClosureCommand> for EffectCommand {
    fn from(payload: CopyClosureCommand) -> Self {
        Self::CopyClosure(payload)
    }
}

#[rustfmt::skip]
impl From<ActivateGenerationCommand> for EffectCommand {
    fn from(payload: ActivateGenerationCommand) -> Self {
        Self::ActivateGeneration(payload)
    }
}

#[rustfmt::skip]
impl From<PathInfoGcCommand> for EffectCommand {
    fn from(payload: PathInfoGcCommand) -> Self {
        Self::PathInfoGc(payload)
    }
}

#[rustfmt::skip]
impl From<HermeticCheckCommand> for EffectCommand {
    fn from(payload: HermeticCheckCommand) -> Self {
        Self::HermeticCheck(payload)
    }
}

#[rustfmt::skip]
impl From<BringUpTestVmCommand> for EffectCommand {
    fn from(payload: BringUpTestVmCommand) -> Self {
        Self::BringUpTestVm(payload)
    }
}

#[rustfmt::skip]
impl From<TearDownTestVmCommand> for EffectCommand {
    fn from(payload: TearDownTestVmCommand) -> Self {
        Self::TearDownTestVm(payload)
    }
}

#[rustfmt::skip]
impl From<ResolvedFlake> for EffectResult {
    fn from(payload: ResolvedFlake) -> Self {
        Self::FlakeResolved(payload)
    }
}

#[rustfmt::skip]
impl From<MaterializedInputs> for EffectResult {
    fn from(payload: MaterializedInputs) -> Self {
        Self::HorizonMaterialized(payload)
    }
}

#[rustfmt::skip]
impl From<EvaluatedClosure> for EffectResult {
    fn from(payload: EvaluatedClosure) -> Self {
        Self::ClosureEvaluated(payload)
    }
}

#[rustfmt::skip]
impl From<BuiltClosure> for EffectResult {
    fn from(payload: BuiltClosure) -> Self {
        Self::ClosureBuilt(payload)
    }
}

#[rustfmt::skip]
impl From<CopiedClosure> for EffectResult {
    fn from(payload: CopiedClosure) -> Self {
        Self::ClosureCopied(payload)
    }
}

#[rustfmt::skip]
impl From<ActivatedGeneration> for EffectResult {
    fn from(payload: ActivatedGeneration) -> Self {
        Self::GenerationActivated(payload)
    }
}

#[rustfmt::skip]
impl From<GarbageCollected> for EffectResult {
    fn from(payload: GarbageCollected) -> Self {
        Self::PathsCollected(payload)
    }
}

#[rustfmt::skip]
impl From<CheckBuilt> for EffectResult {
    fn from(payload: CheckBuilt) -> Self {
        Self::HermeticCheckBuilt(payload)
    }
}

#[rustfmt::skip]
impl From<TestVmBroughtUp> for EffectResult {
    fn from(payload: TestVmBroughtUp) -> Self {
        Self::TestVmBroughtUp(payload)
    }
}

#[rustfmt::skip]
impl From<TestVmTornDown> for EffectResult {
    fn from(payload: TestVmTornDown) -> Self {
        Self::TestVmTornDown(payload)
    }
}

#[rustfmt::skip]
impl From<EffectFailure> for EffectResult {
    fn from(payload: EffectFailure) -> Self {
        Self::EffectFailed(payload)
    }
}

#[rustfmt::skip]
impl From<SignalInput> for NexusWork {
    fn from(payload: SignalInput) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadOutput> for NexusWork {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteOutput> for NexusWork {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<EffectResult> for NexusWork {
    fn from(payload: EffectResult) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadInput> for NexusAction {
    fn from(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteInput> for NexusAction {
    fn from(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCommand> for NexusAction {
    fn from(payload: EffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<SignalOutput> for NexusAction {
    fn from(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<NexusWork> for NexusAction {
    fn from(payload: NexusWork) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<NexusWork> for Input {
    fn from(payload: NexusWork) -> Self {
        Self::NexusWork(payload)
    }
}

#[rustfmt::skip]
impl From<NexusAction> for Output {
    fn from(payload: NexusAction) -> Self {
        Self::NexusAction(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaReadCompleted,
    SemaWriteCompleted,
    EffectCompleted,
}

#[rustfmt::skip]
impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusActionRoute {
    CommandSemaRead,
    CommandSemaWrite,
    CommandEffect,
    ReplyToSignal,
    Continue,
}

#[rustfmt::skip]
impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}
#[rustfmt::skip]
impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => {
                match route {
                    NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                    NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                    NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                    NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
                }
            }
            Self::Action(route) => {
                match route {
                    NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                    NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                    NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                    NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                    NexusActionRoute::Continue => "NexusActionContinue",
                }
            }
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

#[rustfmt::skip]
impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::NexusWork for NexusWork {}

#[rustfmt::skip]
impl triad_runtime::NexusEffectCommand for EffectCommand {}

#[rustfmt::skip]
impl triad_runtime::NexusEffectResult for EffectResult {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub type NexusRunnerNextStep = triad_runtime::NextStep<
    SignalOutput,
    SemaWriteInput,
    SemaReadInput,
    EffectCommand,
    NexusWork,
>;
#[rustfmt::skip]
impl triad_runtime::NexusAction for NexusAction {
    type Reply = SignalOutput;
    type SemaWrite = SemaWriteInput;
    type SemaRead = SemaReadInput;
    type Effect = EffectCommand;
    type Work = NexusWork;
    fn into_next_step(self) -> NexusRunnerNextStep {
        match self {
            Self::CommandSemaWrite(input) => triad_runtime::NextStep::SemaWrite(input),
            Self::CommandSemaRead(input) => triad_runtime::NextStep::SemaRead(input),
            Self::ReplyToSignal(output) => triad_runtime::NextStep::Reply(output),
            Self::CommandEffect(effect) => triad_runtime::NextStep::RunEffect(effect),
            Self::Continue(work) => triad_runtime::NextStep::Continue(work),
        }
    }
}

#[rustfmt::skip]
pub trait NexusEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }
    fn continuation_limit(&self) -> triad_runtime::ContinuationLimit {
        triad_runtime::ContinuationLimit::default()
    }
    fn apply_sema_write(
        &mut self,
        origin_route: OriginRoute,
        input: SemaWriteInput,
    ) -> impl std::future::Future<Output = SemaWriteOutput> + Send + '_;
    fn observe_sema_read(
        &mut self,
        origin_route: OriginRoute,
        input: SemaReadInput,
    ) -> impl std::future::Future<Output = SemaReadOutput> + Send + '_;
    fn run_effect(
        &mut self,
        input: EffectCommand,
    ) -> impl std::future::Future<Output = EffectResult> + Send + '_;
    fn budget_exhausted_reply(
        &self,
        exhausted: triad_runtime::ContinuationExhausted,
    ) -> SignalOutput;
    fn decide(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>;
    fn execute(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> impl std::future::Future<Output = nexus::Nexus<nexus::Action>> + Send + '_
    where
        Self: Sized,
    {
        async move {
            self.trace_nexus_entered();
            let origin_route = input.origin_route();
            let first_work = input.into_root();
            let runner = triad_runtime::Runner::new(self.continuation_limit());
            let mut runner_adapter = NexusRunnerAdapter::new(self, origin_route);
            let reply = runner.drive(&mut runner_adapter, first_work).await;
            let output = NexusAction::reply_to_signal(reply)
                .with_origin_route(origin_route);
            self.trace_nexus_decided();
            output
        }
    }
}

#[rustfmt::skip]
struct NexusRunnerAdapter<'engine, Engine> {
    engine: &'engine mut Engine,
    origin_route: OriginRoute,
}
#[rustfmt::skip]
impl<'engine, Engine> NexusRunnerAdapter<'engine, Engine> {
    fn new(engine: &'engine mut Engine, origin_route: OriginRoute) -> Self {
        Self { engine, origin_route }
    }
}
#[rustfmt::skip]
impl<'engine, Engine> triad_runtime::RunnerEngines
for NexusRunnerAdapter<'engine, Engine>
where
    Engine: NexusEngine,
{
    type Reply = SignalOutput;
    type SemaWrite = SemaWriteInput;
    type SemaRead = SemaReadInput;
    type Effect = EffectCommand;
    type Work = NexusWork;
    fn decide_next_step(
        &mut self,
        work: Self::Work,
    ) -> triad_runtime::runner::RunnerNextStep<Self> {
        let action = NexusEngine::decide(
                self.engine,
                work.with_origin_route(self.origin_route),
            )
            .into_root();
        triad_runtime::NexusAction::into_next_step(action)
    }
    async fn apply_sema_write(&mut self, write: Self::SemaWrite) -> Self::Work {
        let output: SemaWriteOutput = NexusEngine::apply_sema_write(
                self.engine,
                self.origin_route,
                write,
            )
            .await;
        NexusWork::sema_write_completed(output)
    }
    async fn observe_sema_read(&mut self, read: Self::SemaRead) -> Self::Work {
        let output: SemaReadOutput = NexusEngine::observe_sema_read(
                self.engine,
                self.origin_route,
                read,
            )
            .await;
        NexusWork::sema_read_completed(output)
    }
    async fn run_effect(&mut self, effect: Self::Effect) -> Self::Work {
        let output: EffectResult = NexusEngine::run_effect(self.engine, effect).await;
        NexusWork::effect_completed(output)
    }
    fn budget_exhausted_reply(
        &self,
        exhausted: triad_runtime::ContinuationExhausted,
    ) -> Self::Reply {
        NexusEngine::budget_exhausted_reply(self.engine, exhausted)
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
