// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_lojix::schema::lib::Selection as Selection;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationListing as GenerationListing;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::Generation as Generation;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::KeyMaterialQuery as KeyMaterialQuery;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::KeyMaterialReport as KeyMaterialReport;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::EventLogRange as EventLogRange;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::EventLogPosition as EventLogPosition;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentPhaseEvent as DeploymentPhaseEvent;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::CacheRetentionTransitionEvent as CacheRetentionTransitionEvent;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ClusterName as ClusterName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::NodeName as NodeName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::PinLabel as PinLabel;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ClosurePath as ClosurePath;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentIdentifier as DeploymentIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationIdentifier as GenerationIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ContainedRunIdentifier as ContainedRunIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentKind as DeploymentKind;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ActivationKind as ActivationKind;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationSlot as GenerationSlot;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ContainedTarget as ContainedTarget;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ContainedClosurePath as ContainedClosurePath;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::AcceptedContainedDeploy as AcceptedContainedDeploy;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ContainedVerification as ContainedVerification;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ContainedVerificationReport as ContainedVerificationReport;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::RejectedContainedVerification as RejectedContainedVerification;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ContainedRelease as ContainedRelease;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::AppliedContainedRelease as AppliedContainedRelease;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::RejectedRelease as RejectedRelease;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ContainedRunRecord as ContainedRunRecord;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ContainedRunListing as ContainedRunListing;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ContainedRunLookup as ContainedRunLookup;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ContainedRunPhase as ContainedRunPhase;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ContainedOutcome as ContainedOutcome;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::FailureStage as FailureStage;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::SystemDeployment as SystemDeployment;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::HomeDeployment as HomeDeployment;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::PinRequest as PinRequest;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::UnpinRequest as UnpinRequest;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::RetireRequest as RetireRequest;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::AcceptedDeploy as AcceptedDeploy;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::AppliedPin as AppliedPin;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::AppliedUnpin as AppliedUnpin;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::AppliedRetire as AppliedRetire;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadInput {
    QueryGenerations(Selection),
    ReadEventLog(EventLogRange),
    CheckKeyMaterial(KeyMaterialQuery),
    QueryContainedRuns(ContainedRunLookup),
    VerifyContainedRun(ContainedVerification),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadOutput {
    GenerationsQueried(GenerationListing),
    EventLogRead(EventLogPage),
    KeyMaterialChecked(KeyMaterialReport),
    ContainedRunsQueried(ContainedRunListing),
    ContainedVerified(ContainedVerificationReport),
    ContainedVerificationRejected(RejectedContainedVerification),
    ReadMissed(RejectionReport),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeploymentEvents(Vec<DeploymentPhaseEvent>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetentionEvents(Vec<CacheRetentionTransitionEvent>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogPage {
    pub deployment_events: DeploymentEvents,
    pub retention_events: RetentionEvents,
    pub state_marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteInput {
    RecordDeploySubmitted(DeploySubmission),
    RecordPhaseTransition(DeploymentPhaseEvent),
    RecordGenerationActivated(ActivationCommit),
    PinGeneration(PinRequest),
    UnpinGeneration(UnpinRequest),
    RetireGeneration(RetireRequest),
    RecordContainerTransition(ContainerTransition),
    RecordContainedRun(ContainedRunRecord),
    ReleaseContainedRun(ContainedRelease),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeploySubmission {
    System(SystemDeployment),
    Home(HomeDeployment),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivationCommit {
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_slot: GenerationSlot,
    pub closure_path: ClosurePath,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerTransition {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub container: ContainerName,
    pub state: ContainerState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ContainerState {
    Starting,
    Started,
    Stopping,
    Stopped,
    Failed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteOutput {
    DeploySubmitted(AcceptedDeploy),
    PhaseRecorded(PhaseReceipt),
    GenerationActivated(AppliedActivation),
    GenerationPinned(AppliedPin),
    GenerationUnpinned(AppliedUnpin),
    GenerationRetired(AppliedRetire),
    ContainerRecorded(ContainerReceipt),
    ContainedRunRecorded(AcceptedContainedDeploy),
    ContainedRunReleased(AppliedContainedRelease),
    ContainedReleaseRejected(RejectedRelease),
    WriteRejected(RejectionReport),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PhaseReceipt {
    pub event_log_position: EventLogPosition,
    pub state_marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedActivation {
    pub generation_identifier: GenerationIdentifier,
    pub generation_slot: GenerationSlot,
    pub state_marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerReceipt {
    pub event_log_position: EventLogPosition,
    pub state_marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionReport {
    pub reason: RejectionReason,
    pub marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RejectionReason {
    GenerationUnknown,
    NodeUnknown,
    ClusterUnknown,
    PlanNotApproved,
    PinLabelInUse,
    PinLabelUnknown,
    GenerationActive,
    GenerationPinned,
    EventLogPositionOutOfRange,
    ProposalSourceUnreachable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommitSequence(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateDigest(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LiveSetEntries(Vec<LiveGeneration>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LiveSetTable(LiveSetEntries);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LiveGeneration {
    pub deployment_identifier: DeploymentIdentifier,
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub deployment_kind: DeploymentKind,
    pub activation_kind: ActivationKind,
    pub generation_slot: GenerationSlot,
    pub closure_path: ClosurePath,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GcRoots(Vec<GcRoot>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GcRootsTable(GcRoots);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Label(Option<PinLabel>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GcRoot {
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_slot: GenerationSlot,
    pub closure_path: ClosurePath,
    pub label: Label,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogEntries(Vec<EventLogEntry>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogTable(EventLogEntries);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogEntry {
    pub event_log_position: EventLogPosition,
    pub record: LoggedEvent,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum LoggedEvent {
    Deployment(DeploymentPhaseEvent),
    CacheRetention(CacheRetentionTransitionEvent),
    Container(ContainerLifecycleRecord),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerLifecycleRecords(Vec<ContainerLifecycleRecord>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerLifecycleTable(ContainerLifecycleRecords);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerLifecycleRecord {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub container: ContainerName,
    pub state: ContainerState,
    pub event_log_position: EventLogPosition,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployJobs(Vec<DeployJob>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployJobTable(DeployJobs);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployJobClosurePath(Option<ClosurePath>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ResolvedTarget(Option<String>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BootOnceUnit(Option<String>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployJob {
    pub deployment_identifier: DeploymentIdentifier,
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub phase: DeployJobPhase,
    pub deploy_job_closure_path: DeployJobClosurePath,
    pub resolved_target: ResolvedTarget,
    pub boot_once_unit: BootOnceUnit,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DeployJobPhase {
    Submitted,
    Building,
    Built,
    Copying,
    Activating,
    Activated,
    Failed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoredContainedRuns(Vec<StoredContainedRun>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainedRunTable(StoredContainedRuns);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoredContainedRun {
    pub contained_run_identifier: ContainedRunIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub host: NodeName,
    pub target: ContainedTarget,
    pub phase: ContainedRunPhase,
    pub outcome: ContainedOutcome,
    pub contained_closure_path: ContainedClosurePath,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SemaReadInput(SemaReadInput),
    SemaWriteInput(SemaWriteInput),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SemaReadOutput(SemaReadOutput),
    SemaWriteOutput(SemaWriteOutput),
}

#[rustfmt::skip]
impl DeploymentEvents {
    pub fn new(payload: Vec<DeploymentPhaseEvent>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<DeploymentPhaseEvent> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<DeploymentPhaseEvent> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<DeploymentPhaseEvent>> for DeploymentEvents {
    fn from(payload: Vec<DeploymentPhaseEvent>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetentionEvents {
    pub fn new(payload: Vec<CacheRetentionTransitionEvent>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<CacheRetentionTransitionEvent> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<CacheRetentionTransitionEvent> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<CacheRetentionTransitionEvent>> for RetentionEvents {
    fn from(payload: Vec<CacheRetentionTransitionEvent>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ContainerName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ContainerName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommitSequence {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CommitSequence {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StateDigest {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for StateDigest {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LiveSetEntries {
    pub fn new(payload: Vec<LiveGeneration>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<LiveGeneration> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<LiveGeneration> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<LiveGeneration>> for LiveSetEntries {
    fn from(payload: Vec<LiveGeneration>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LiveSetTable {
    pub fn new(payload: LiveSetEntries) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LiveSetEntries {
        &self.0
    }
    pub fn into_payload(self) -> LiveSetEntries {
        self.0
    }
}
#[rustfmt::skip]
impl From<LiveSetEntries> for LiveSetTable {
    fn from(payload: LiveSetEntries) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GcRoots {
    pub fn new(payload: Vec<GcRoot>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<GcRoot> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<GcRoot> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<GcRoot>> for GcRoots {
    fn from(payload: Vec<GcRoot>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GcRootsTable {
    pub fn new(payload: GcRoots) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &GcRoots {
        &self.0
    }
    pub fn into_payload(self) -> GcRoots {
        self.0
    }
}
#[rustfmt::skip]
impl From<GcRoots> for GcRootsTable {
    fn from(payload: GcRoots) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Label {
    pub fn new(payload: Option<PinLabel>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<PinLabel> {
        &self.0
    }
    pub fn into_payload(self) -> Option<PinLabel> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<PinLabel>> for Label {
    fn from(payload: Option<PinLabel>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EventLogEntries {
    pub fn new(payload: Vec<EventLogEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<EventLogEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<EventLogEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<EventLogEntry>> for EventLogEntries {
    fn from(payload: Vec<EventLogEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EventLogTable {
    pub fn new(payload: EventLogEntries) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EventLogEntries {
        &self.0
    }
    pub fn into_payload(self) -> EventLogEntries {
        self.0
    }
}
#[rustfmt::skip]
impl From<EventLogEntries> for EventLogTable {
    fn from(payload: EventLogEntries) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ContainerLifecycleRecords {
    pub fn new(payload: Vec<ContainerLifecycleRecord>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ContainerLifecycleRecord> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ContainerLifecycleRecord> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ContainerLifecycleRecord>> for ContainerLifecycleRecords {
    fn from(payload: Vec<ContainerLifecycleRecord>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ContainerLifecycleTable {
    pub fn new(payload: ContainerLifecycleRecords) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ContainerLifecycleRecords {
        &self.0
    }
    pub fn into_payload(self) -> ContainerLifecycleRecords {
        self.0
    }
}
#[rustfmt::skip]
impl From<ContainerLifecycleRecords> for ContainerLifecycleTable {
    fn from(payload: ContainerLifecycleRecords) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeployJobs {
    pub fn new(payload: Vec<DeployJob>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<DeployJob> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<DeployJob> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<DeployJob>> for DeployJobs {
    fn from(payload: Vec<DeployJob>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeployJobTable {
    pub fn new(payload: DeployJobs) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DeployJobs {
        &self.0
    }
    pub fn into_payload(self) -> DeployJobs {
        self.0
    }
}
#[rustfmt::skip]
impl From<DeployJobs> for DeployJobTable {
    fn from(payload: DeployJobs) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeployJobClosurePath {
    pub fn new(payload: Option<ClosurePath>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<ClosurePath> {
        &self.0
    }
    pub fn into_payload(self) -> Option<ClosurePath> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<ClosurePath>> for DeployJobClosurePath {
    fn from(payload: Option<ClosurePath>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ResolvedTarget {
    pub fn new(payload: Option<String>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<String> {
        &self.0
    }
    pub fn into_payload(self) -> Option<String> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<String>> for ResolvedTarget {
    fn from(payload: Option<String>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl BootOnceUnit {
    pub fn new(payload: Option<String>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<String> {
        &self.0
    }
    pub fn into_payload(self) -> Option<String> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<String>> for BootOnceUnit {
    fn from(payload: Option<String>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StoredContainedRuns {
    pub fn new(payload: Vec<StoredContainedRun>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<StoredContainedRun> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<StoredContainedRun> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<StoredContainedRun>> for StoredContainedRuns {
    fn from(payload: Vec<StoredContainedRun>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ContainedRunTable {
    pub fn new(payload: StoredContainedRuns) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StoredContainedRuns {
        &self.0
    }
    pub fn into_payload(self) -> StoredContainedRuns {
        self.0
    }
}
#[rustfmt::skip]
impl From<StoredContainedRuns> for ContainedRunTable {
    fn from(payload: StoredContainedRuns) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn query_generations(payload: Selection) -> Self {
        Self::QueryGenerations(payload)
    }
    pub fn read_event_log(payload: EventLogRange) -> Self {
        Self::ReadEventLog(payload)
    }
    pub fn check_key_material(payload: KeyMaterialQuery) -> Self {
        Self::CheckKeyMaterial(payload)
    }
    pub fn query_contained_runs(payload: ContainedRunLookup) -> Self {
        Self::QueryContainedRuns(payload)
    }
    pub fn verify_contained_run(payload: ContainedVerification) -> Self {
        Self::VerifyContainedRun(payload)
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn generations_queried(payload: GenerationListing) -> Self {
        Self::GenerationsQueried(payload)
    }
    pub fn event_log_read(payload: EventLogPage) -> Self {
        Self::EventLogRead(payload)
    }
    pub fn key_material_checked(payload: KeyMaterialReport) -> Self {
        Self::KeyMaterialChecked(payload)
    }
    pub fn contained_runs_queried(payload: ContainedRunListing) -> Self {
        Self::ContainedRunsQueried(payload)
    }
    pub fn contained_verified(payload: ContainedVerificationReport) -> Self {
        Self::ContainedVerified(payload)
    }
    pub fn contained_verification_rejected(
        payload: RejectedContainedVerification,
    ) -> Self {
        Self::ContainedVerificationRejected(payload)
    }
    pub fn read_missed(payload: RejectionReport) -> Self {
        Self::ReadMissed(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn record_deploy_submitted(payload: DeploySubmission) -> Self {
        Self::RecordDeploySubmitted(payload)
    }
    pub fn record_phase_transition(payload: DeploymentPhaseEvent) -> Self {
        Self::RecordPhaseTransition(payload)
    }
    pub fn record_generation_activated(payload: ActivationCommit) -> Self {
        Self::RecordGenerationActivated(payload)
    }
    pub fn pin_generation(payload: PinRequest) -> Self {
        Self::PinGeneration(payload)
    }
    pub fn unpin_generation(payload: UnpinRequest) -> Self {
        Self::UnpinGeneration(payload)
    }
    pub fn retire_generation(payload: RetireRequest) -> Self {
        Self::RetireGeneration(payload)
    }
    pub fn record_container_transition(payload: ContainerTransition) -> Self {
        Self::RecordContainerTransition(payload)
    }
    pub fn record_contained_run(payload: ContainedRunRecord) -> Self {
        Self::RecordContainedRun(payload)
    }
    pub fn release_contained_run(payload: ContainedRelease) -> Self {
        Self::ReleaseContainedRun(payload)
    }
}

#[rustfmt::skip]
impl DeploySubmission {
    pub fn system(payload: SystemDeployment) -> Self {
        Self::System(payload)
    }
    pub fn home(payload: HomeDeployment) -> Self {
        Self::Home(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn deploy_submitted(payload: AcceptedDeploy) -> Self {
        Self::DeploySubmitted(payload)
    }
    pub fn phase_recorded(payload: PhaseReceipt) -> Self {
        Self::PhaseRecorded(payload)
    }
    pub fn generation_activated(payload: AppliedActivation) -> Self {
        Self::GenerationActivated(payload)
    }
    pub fn generation_pinned(payload: AppliedPin) -> Self {
        Self::GenerationPinned(payload)
    }
    pub fn generation_unpinned(payload: AppliedUnpin) -> Self {
        Self::GenerationUnpinned(payload)
    }
    pub fn generation_retired(payload: AppliedRetire) -> Self {
        Self::GenerationRetired(payload)
    }
    pub fn container_recorded(payload: ContainerReceipt) -> Self {
        Self::ContainerRecorded(payload)
    }
    pub fn contained_run_recorded(payload: AcceptedContainedDeploy) -> Self {
        Self::ContainedRunRecorded(payload)
    }
    pub fn contained_run_released(payload: AppliedContainedRelease) -> Self {
        Self::ContainedRunReleased(payload)
    }
    pub fn contained_release_rejected(payload: RejectedRelease) -> Self {
        Self::ContainedReleaseRejected(payload)
    }
    pub fn write_rejected(payload: RejectionReport) -> Self {
        Self::WriteRejected(payload)
    }
}

#[rustfmt::skip]
impl LoggedEvent {
    pub fn deployment(payload: DeploymentPhaseEvent) -> Self {
        Self::Deployment(payload)
    }
    pub fn cache_retention(payload: CacheRetentionTransitionEvent) -> Self {
        Self::CacheRetention(payload)
    }
    pub fn container(payload: ContainerLifecycleRecord) -> Self {
        Self::Container(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn sema_read_input(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }
    pub fn sema_write_input(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn sema_read_output(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }
    pub fn sema_write_output(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

#[rustfmt::skip]
impl From<Selection> for SemaReadInput {
    fn from(payload: Selection) -> Self {
        Self::QueryGenerations(payload)
    }
}

#[rustfmt::skip]
impl From<EventLogRange> for SemaReadInput {
    fn from(payload: EventLogRange) -> Self {
        Self::ReadEventLog(payload)
    }
}

#[rustfmt::skip]
impl From<KeyMaterialQuery> for SemaReadInput {
    fn from(payload: KeyMaterialQuery) -> Self {
        Self::CheckKeyMaterial(payload)
    }
}

#[rustfmt::skip]
impl From<ContainedRunLookup> for SemaReadInput {
    fn from(payload: ContainedRunLookup) -> Self {
        Self::QueryContainedRuns(payload)
    }
}

#[rustfmt::skip]
impl From<ContainedVerification> for SemaReadInput {
    fn from(payload: ContainedVerification) -> Self {
        Self::VerifyContainedRun(payload)
    }
}

#[rustfmt::skip]
impl From<GenerationListing> for SemaReadOutput {
    fn from(payload: GenerationListing) -> Self {
        Self::GenerationsQueried(payload)
    }
}

#[rustfmt::skip]
impl From<EventLogPage> for SemaReadOutput {
    fn from(payload: EventLogPage) -> Self {
        Self::EventLogRead(payload)
    }
}

#[rustfmt::skip]
impl From<KeyMaterialReport> for SemaReadOutput {
    fn from(payload: KeyMaterialReport) -> Self {
        Self::KeyMaterialChecked(payload)
    }
}

#[rustfmt::skip]
impl From<ContainedRunListing> for SemaReadOutput {
    fn from(payload: ContainedRunListing) -> Self {
        Self::ContainedRunsQueried(payload)
    }
}

#[rustfmt::skip]
impl From<ContainedVerificationReport> for SemaReadOutput {
    fn from(payload: ContainedVerificationReport) -> Self {
        Self::ContainedVerified(payload)
    }
}

#[rustfmt::skip]
impl From<RejectedContainedVerification> for SemaReadOutput {
    fn from(payload: RejectedContainedVerification) -> Self {
        Self::ContainedVerificationRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RejectionReport> for SemaReadOutput {
    fn from(payload: RejectionReport) -> Self {
        Self::ReadMissed(payload)
    }
}

#[rustfmt::skip]
impl From<DeploySubmission> for SemaWriteInput {
    fn from(payload: DeploySubmission) -> Self {
        Self::RecordDeploySubmitted(payload)
    }
}

#[rustfmt::skip]
impl From<DeploymentPhaseEvent> for SemaWriteInput {
    fn from(payload: DeploymentPhaseEvent) -> Self {
        Self::RecordPhaseTransition(payload)
    }
}

#[rustfmt::skip]
impl From<ActivationCommit> for SemaWriteInput {
    fn from(payload: ActivationCommit) -> Self {
        Self::RecordGenerationActivated(payload)
    }
}

#[rustfmt::skip]
impl From<PinRequest> for SemaWriteInput {
    fn from(payload: PinRequest) -> Self {
        Self::PinGeneration(payload)
    }
}

#[rustfmt::skip]
impl From<UnpinRequest> for SemaWriteInput {
    fn from(payload: UnpinRequest) -> Self {
        Self::UnpinGeneration(payload)
    }
}

#[rustfmt::skip]
impl From<RetireRequest> for SemaWriteInput {
    fn from(payload: RetireRequest) -> Self {
        Self::RetireGeneration(payload)
    }
}

#[rustfmt::skip]
impl From<ContainerTransition> for SemaWriteInput {
    fn from(payload: ContainerTransition) -> Self {
        Self::RecordContainerTransition(payload)
    }
}

#[rustfmt::skip]
impl From<ContainedRunRecord> for SemaWriteInput {
    fn from(payload: ContainedRunRecord) -> Self {
        Self::RecordContainedRun(payload)
    }
}

#[rustfmt::skip]
impl From<ContainedRelease> for SemaWriteInput {
    fn from(payload: ContainedRelease) -> Self {
        Self::ReleaseContainedRun(payload)
    }
}

#[rustfmt::skip]
impl From<SystemDeployment> for DeploySubmission {
    fn from(payload: SystemDeployment) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<HomeDeployment> for DeploySubmission {
    fn from(payload: HomeDeployment) -> Self {
        Self::Home(payload)
    }
}

#[rustfmt::skip]
impl From<AcceptedDeploy> for SemaWriteOutput {
    fn from(payload: AcceptedDeploy) -> Self {
        Self::DeploySubmitted(payload)
    }
}

#[rustfmt::skip]
impl From<PhaseReceipt> for SemaWriteOutput {
    fn from(payload: PhaseReceipt) -> Self {
        Self::PhaseRecorded(payload)
    }
}

#[rustfmt::skip]
impl From<AppliedActivation> for SemaWriteOutput {
    fn from(payload: AppliedActivation) -> Self {
        Self::GenerationActivated(payload)
    }
}

#[rustfmt::skip]
impl From<AppliedPin> for SemaWriteOutput {
    fn from(payload: AppliedPin) -> Self {
        Self::GenerationPinned(payload)
    }
}

#[rustfmt::skip]
impl From<AppliedUnpin> for SemaWriteOutput {
    fn from(payload: AppliedUnpin) -> Self {
        Self::GenerationUnpinned(payload)
    }
}

#[rustfmt::skip]
impl From<AppliedRetire> for SemaWriteOutput {
    fn from(payload: AppliedRetire) -> Self {
        Self::GenerationRetired(payload)
    }
}

#[rustfmt::skip]
impl From<ContainerReceipt> for SemaWriteOutput {
    fn from(payload: ContainerReceipt) -> Self {
        Self::ContainerRecorded(payload)
    }
}

#[rustfmt::skip]
impl From<AcceptedContainedDeploy> for SemaWriteOutput {
    fn from(payload: AcceptedContainedDeploy) -> Self {
        Self::ContainedRunRecorded(payload)
    }
}

#[rustfmt::skip]
impl From<AppliedContainedRelease> for SemaWriteOutput {
    fn from(payload: AppliedContainedRelease) -> Self {
        Self::ContainedRunReleased(payload)
    }
}

#[rustfmt::skip]
impl From<RejectedRelease> for SemaWriteOutput {
    fn from(payload: RejectedRelease) -> Self {
        Self::ContainedReleaseRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RejectionReport> for SemaWriteOutput {
    fn from(payload: RejectionReport) -> Self {
        Self::WriteRejected(payload)
    }
}

#[rustfmt::skip]
impl From<DeploymentPhaseEvent> for LoggedEvent {
    fn from(payload: DeploymentPhaseEvent) -> Self {
        Self::Deployment(payload)
    }
}

#[rustfmt::skip]
impl From<CacheRetentionTransitionEvent> for LoggedEvent {
    fn from(payload: CacheRetentionTransitionEvent) -> Self {
        Self::CacheRetention(payload)
    }
}

#[rustfmt::skip]
impl From<ContainerLifecycleRecord> for LoggedEvent {
    fn from(payload: ContainerLifecycleRecord) -> Self {
        Self::Container(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadInput> for Input {
    fn from(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteInput> for Input {
    fn from(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadOutput> for Output {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteOutput> for Output {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaReadInputRoute {
    QueryGenerations,
    ReadEventLog,
    CheckKeyMaterial,
    QueryContainedRuns,
    VerifyContainedRun,
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn route(&self) -> SemaReadInputRoute {
        match self {
            Self::QueryGenerations(_) => SemaReadInputRoute::QueryGenerations,
            Self::ReadEventLog(_) => SemaReadInputRoute::ReadEventLog,
            Self::CheckKeyMaterial(_) => SemaReadInputRoute::CheckKeyMaterial,
            Self::QueryContainedRuns(_) => SemaReadInputRoute::QueryContainedRuns,
            Self::VerifyContainedRun(_) => SemaReadInputRoute::VerifyContainedRun,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaReadOutputRoute {
    GenerationsQueried,
    EventLogRead,
    KeyMaterialChecked,
    ContainedRunsQueried,
    ContainedVerified,
    ContainedVerificationRejected,
    ReadMissed,
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn route(&self) -> SemaReadOutputRoute {
        match self {
            Self::GenerationsQueried(_) => SemaReadOutputRoute::GenerationsQueried,
            Self::EventLogRead(_) => SemaReadOutputRoute::EventLogRead,
            Self::KeyMaterialChecked(_) => SemaReadOutputRoute::KeyMaterialChecked,
            Self::ContainedRunsQueried(_) => SemaReadOutputRoute::ContainedRunsQueried,
            Self::ContainedVerified(_) => SemaReadOutputRoute::ContainedVerified,
            Self::ContainedVerificationRejected(_) => {
                SemaReadOutputRoute::ContainedVerificationRejected
            }
            Self::ReadMissed(_) => SemaReadOutputRoute::ReadMissed,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaWriteInputRoute {
    RecordDeploySubmitted,
    RecordPhaseTransition,
    RecordGenerationActivated,
    PinGeneration,
    UnpinGeneration,
    RetireGeneration,
    RecordContainerTransition,
    RecordContainedRun,
    ReleaseContainedRun,
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn route(&self) -> SemaWriteInputRoute {
        match self {
            Self::RecordDeploySubmitted(_) => SemaWriteInputRoute::RecordDeploySubmitted,
            Self::RecordPhaseTransition(_) => SemaWriteInputRoute::RecordPhaseTransition,
            Self::RecordGenerationActivated(_) => {
                SemaWriteInputRoute::RecordGenerationActivated
            }
            Self::PinGeneration(_) => SemaWriteInputRoute::PinGeneration,
            Self::UnpinGeneration(_) => SemaWriteInputRoute::UnpinGeneration,
            Self::RetireGeneration(_) => SemaWriteInputRoute::RetireGeneration,
            Self::RecordContainerTransition(_) => {
                SemaWriteInputRoute::RecordContainerTransition
            }
            Self::RecordContainedRun(_) => SemaWriteInputRoute::RecordContainedRun,
            Self::ReleaseContainedRun(_) => SemaWriteInputRoute::ReleaseContainedRun,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaWriteOutputRoute {
    DeploySubmitted,
    PhaseRecorded,
    GenerationActivated,
    GenerationPinned,
    GenerationUnpinned,
    GenerationRetired,
    ContainerRecorded,
    ContainedRunRecorded,
    ContainedRunReleased,
    ContainedReleaseRejected,
    WriteRejected,
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn route(&self) -> SemaWriteOutputRoute {
        match self {
            Self::DeploySubmitted(_) => SemaWriteOutputRoute::DeploySubmitted,
            Self::PhaseRecorded(_) => SemaWriteOutputRoute::PhaseRecorded,
            Self::GenerationActivated(_) => SemaWriteOutputRoute::GenerationActivated,
            Self::GenerationPinned(_) => SemaWriteOutputRoute::GenerationPinned,
            Self::GenerationUnpinned(_) => SemaWriteOutputRoute::GenerationUnpinned,
            Self::GenerationRetired(_) => SemaWriteOutputRoute::GenerationRetired,
            Self::ContainerRecorded(_) => SemaWriteOutputRoute::ContainerRecorded,
            Self::ContainedRunRecorded(_) => SemaWriteOutputRoute::ContainedRunRecorded,
            Self::ContainedRunReleased(_) => SemaWriteOutputRoute::ContainedRunReleased,
            Self::ContainedReleaseRejected(_) => {
                SemaWriteOutputRoute::ContainedReleaseRejected
            }
            Self::WriteRejected(_) => SemaWriteOutputRoute::WriteRejected,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(SemaWriteInputRoute),
    ReadInput(SemaReadInputRoute),
    WriteOutput(SemaWriteOutputRoute),
    ReadOutput(SemaReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
#[rustfmt::skip]
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    SemaWriteInputRoute::RecordDeploySubmitted => {
                        "SemaWriteInputRecordDeploySubmitted"
                    }
                    SemaWriteInputRoute::RecordPhaseTransition => {
                        "SemaWriteInputRecordPhaseTransition"
                    }
                    SemaWriteInputRoute::RecordGenerationActivated => {
                        "SemaWriteInputRecordGenerationActivated"
                    }
                    SemaWriteInputRoute::PinGeneration => "SemaWriteInputPinGeneration",
                    SemaWriteInputRoute::UnpinGeneration => {
                        "SemaWriteInputUnpinGeneration"
                    }
                    SemaWriteInputRoute::RetireGeneration => {
                        "SemaWriteInputRetireGeneration"
                    }
                    SemaWriteInputRoute::RecordContainerTransition => {
                        "SemaWriteInputRecordContainerTransition"
                    }
                    SemaWriteInputRoute::RecordContainedRun => {
                        "SemaWriteInputRecordContainedRun"
                    }
                    SemaWriteInputRoute::ReleaseContainedRun => {
                        "SemaWriteInputReleaseContainedRun"
                    }
                }
            }
            Self::ReadInput(route) => {
                match route {
                    SemaReadInputRoute::QueryGenerations => {
                        "SemaReadInputQueryGenerations"
                    }
                    SemaReadInputRoute::ReadEventLog => "SemaReadInputReadEventLog",
                    SemaReadInputRoute::CheckKeyMaterial => {
                        "SemaReadInputCheckKeyMaterial"
                    }
                    SemaReadInputRoute::QueryContainedRuns => {
                        "SemaReadInputQueryContainedRuns"
                    }
                    SemaReadInputRoute::VerifyContainedRun => {
                        "SemaReadInputVerifyContainedRun"
                    }
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    SemaWriteOutputRoute::DeploySubmitted => {
                        "SemaWriteOutputDeploySubmitted"
                    }
                    SemaWriteOutputRoute::PhaseRecorded => "SemaWriteOutputPhaseRecorded",
                    SemaWriteOutputRoute::GenerationActivated => {
                        "SemaWriteOutputGenerationActivated"
                    }
                    SemaWriteOutputRoute::GenerationPinned => {
                        "SemaWriteOutputGenerationPinned"
                    }
                    SemaWriteOutputRoute::GenerationUnpinned => {
                        "SemaWriteOutputGenerationUnpinned"
                    }
                    SemaWriteOutputRoute::GenerationRetired => {
                        "SemaWriteOutputGenerationRetired"
                    }
                    SemaWriteOutputRoute::ContainerRecorded => {
                        "SemaWriteOutputContainerRecorded"
                    }
                    SemaWriteOutputRoute::ContainedRunRecorded => {
                        "SemaWriteOutputContainedRunRecorded"
                    }
                    SemaWriteOutputRoute::ContainedRunReleased => {
                        "SemaWriteOutputContainedRunReleased"
                    }
                    SemaWriteOutputRoute::ContainedReleaseRejected => {
                        "SemaWriteOutputContainedReleaseRejected"
                    }
                    SemaWriteOutputRoute::WriteRejected => "SemaWriteOutputWriteRejected",
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    SemaReadOutputRoute::GenerationsQueried => {
                        "SemaReadOutputGenerationsQueried"
                    }
                    SemaReadOutputRoute::EventLogRead => "SemaReadOutputEventLogRead",
                    SemaReadOutputRoute::KeyMaterialChecked => {
                        "SemaReadOutputKeyMaterialChecked"
                    }
                    SemaReadOutputRoute::ContainedRunsQueried => {
                        "SemaReadOutputContainedRunsQueried"
                    }
                    SemaReadOutputRoute::ContainedVerified => {
                        "SemaReadOutputContainedVerified"
                    }
                    SemaReadOutputRoute::ContainedVerificationRejected => {
                        "SemaReadOutputContainedVerificationRejected"
                    }
                    SemaReadOutputRoute::ReadMissed => "SemaReadOutputReadMissed",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Sema(SemaObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::SemaWriteInput;
    pub type WriteOutput = super::SemaWriteOutput;
    pub type ReadInput = super::SemaReadInput;
    pub type ReadOutput = super::SemaReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::SemaWriteInput for SemaWriteInput {}

#[rustfmt::skip]
impl triad_runtime::SemaWriteOutput for SemaWriteOutput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadInput for SemaReadInput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadOutput for SemaReadOutput {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SemaEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
