// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_lojix::schema::lib::Selection as Selection;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationListing as GenerationListing;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::Generation as Generation;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::KeyMaterialQuery as KeyMaterialQuery;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::KeyMaterialReport as KeyMaterialReport;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::EventLogRange as EventLogRange;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::EventLogPosition as EventLogPosition;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentPhaseEvent as DeploymentPhaseEvent;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::CacheRetentionTransitionEvent as CacheRetentionTransitionEvent;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ClusterName as ClusterName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::NodeName as NodeName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::PinLabel as PinLabel;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ClosurePath as ClosurePath;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::FlakeReference as FlakeReference;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::SourceRevisionPolicy as SourceRevisionPolicy;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::SourceRevisionRecord as SourceRevisionRecord;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentIdentifier as DeploymentIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationIdentifier as GenerationIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestRunIdentifier as TestRunIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationArtifact as GenerationArtifact;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ActivationEffect as ActivationEffect;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationSlot as GenerationSlot;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestMode as TestMode;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestRunRecord as TestRunRecord;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestRunListing as TestRunListing;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestRunLookup as TestRunLookup;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestRunPhase as TestRunPhase;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestOutcome as TestOutcome;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::FailureStage as FailureStage;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::HostDeployment as HostDeployment;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::UserEnvironmentDeployment as UserEnvironmentDeployment;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::PinRequest as PinRequest;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::UnpinRequest as UnpinRequest;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::RetireRequest as RetireRequest;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::DeployHandle as DeployHandle;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::AcceptedTest as AcceptedTest;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::AppliedPin as AppliedPin;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::AppliedUnpin as AppliedUnpin;
#[rustfmt::skip]
pub use meta_signal_lojix::schema::lib::AppliedRetire as AppliedRetire;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadInput {
    QueryGenerations(Selection),
    ReadEventLog(EventLogRange),
    CheckKeyMaterial(KeyMaterialQuery),
    QueryTestRuns(TestRunLookup),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadOutput {
    GenerationsQueried(GenerationListing),
    EventLogRead(EventLogPage),
    KeyMaterialChecked(KeyMaterialReport),
    TestRunsQueried(TestRunListing),
    ReadMissed(RejectionReport),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogPage {
    pub deployment_events: Vec<DeploymentPhaseEvent>,
    pub retention_events: Vec<CacheRetentionTransitionEvent>,
    pub state_marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteInput {
    RecordDeploySubmitted(DeploySubmission),
    RecordPhaseTransition(DeploymentPhaseEvent),
    RecordGenerationActivated(ActivationCommit),
    PinGeneration(PinRequest),
    UnpinGeneration(UnpinRequest),
    RetireGeneration(RetireRequest),
    RecordContainerTransition(ContainerTransition),
    RecordTestRun(TestRunRecord),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeploySubmission {
    Host(HostDeployment),
    UserEnvironment(UserEnvironmentDeployment),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivationCommit {
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_slot: GenerationSlot,
    pub closure_path: ClosurePath,
    pub source_revision_record: SourceRevisionRecord,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerTransition {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub container: ContainerName,
    pub state: ContainerState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ContainerState {
    Starting,
    Started,
    Stopping,
    Stopped,
    Failed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteOutput {
    DeploySubmitted(DeployHandle),
    PhaseRecorded(PhaseReceipt),
    GenerationActivated(AppliedActivation),
    GenerationPinned(AppliedPin),
    GenerationUnpinned(AppliedUnpin),
    GenerationRetired(AppliedRetire),
    ContainerRecorded(ContainerReceipt),
    TestRunRecorded(AcceptedTest),
    WriteRejected(RejectionReport),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PhaseReceipt {
    pub event_log_position: EventLogPosition,
    pub state_marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedActivation {
    pub generation_identifier: GenerationIdentifier,
    pub generation_slot: GenerationSlot,
    pub state_marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerReceipt {
    pub event_log_position: EventLogPosition,
    pub state_marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionReport {
    pub reason: RejectionReason,
    pub marker: StateMarker,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RejectionReason {
    GenerationUnknown,
    NodeUnknown,
    ClusterUnknown,
    PlanNotApproved,
    PinLabelInUse,
    PinLabelUnknown,
    GenerationActive,
    GenerationPinned,
    EventLogPositionOutOfRange,
    ProposalSourceUnreachable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommitSequence(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateDigest(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LiveSetTable(Vec<LiveGeneration>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LiveGeneration {
    pub deployment_identifier: DeploymentIdentifier,
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_artifact: GenerationArtifact,
    pub activation_effect: ActivationEffect,
    pub generation_slot: GenerationSlot,
    pub closure_path: ClosurePath,
    pub source_revision_record: SourceRevisionRecord,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GcRootsTable(Vec<GcRoot>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GcRoot {
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_slot: GenerationSlot,
    pub closure_path: ClosurePath,
    pub label: Option<PinLabel>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogTable(Vec<EventLogEntry>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EventLogEntry {
    pub event_log_position: EventLogPosition,
    pub record: LoggedEvent,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum LoggedEvent {
    Deployment(DeploymentPhaseEvent),
    CacheRetention(CacheRetentionTransitionEvent),
    Container(ContainerLifecycleRecord),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerLifecycleTable(Vec<ContainerLifecycleRecord>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContainerLifecycleRecord {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub container: ContainerName,
    pub state: ContainerState,
    pub event_log_position: EventLogPosition,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployJobTable(Vec<DeployJob>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployJob {
    pub deployment_identifier: DeploymentIdentifier,
    pub generation_identifier: GenerationIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub phase: DeployJobPhase,
    pub closure_path: Option<ClosurePath>,
    pub source_revision_policy: SourceRevisionPolicy,
    pub requested_ref: FlakeReference,
    pub resolved_ref: Option<FlakeReference>,
    pub resolved_revision: Option<String>,
    pub resolved_target: Option<String>,
    pub boot_once_unit: Option<String>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DeployJobPhase {
    Submitted,
    Building,
    Built,
    Copying,
    Activating,
    Activated,
    Failed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestRunTable(Vec<StoredTestRun>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoredTestRun {
    pub test_run_identifier: TestRunIdentifier,
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub host: NodeName,
    pub mode: TestMode,
    pub phase: TestRunPhase,
    pub outcome: TestOutcome,
    pub closure_path: Option<ClosurePath>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SemaReadInput(SemaReadInput),
    SemaWriteInput(SemaWriteInput),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SemaReadOutput(SemaReadOutput),
    SemaWriteOutput(SemaWriteOutput),
}

#[rustfmt::skip]
impl ContainerName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ContainerName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommitSequence {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CommitSequence {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StateDigest {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for StateDigest {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LiveSetTable {
    pub fn new(payload: Vec<LiveGeneration>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<LiveGeneration> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<LiveGeneration> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<LiveGeneration>> for LiveSetTable {
    fn from(payload: Vec<LiveGeneration>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GcRootsTable {
    pub fn new(payload: Vec<GcRoot>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<GcRoot> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<GcRoot> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<GcRoot>> for GcRootsTable {
    fn from(payload: Vec<GcRoot>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EventLogTable {
    pub fn new(payload: Vec<EventLogEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<EventLogEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<EventLogEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<EventLogEntry>> for EventLogTable {
    fn from(payload: Vec<EventLogEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ContainerLifecycleTable {
    pub fn new(payload: Vec<ContainerLifecycleRecord>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ContainerLifecycleRecord> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ContainerLifecycleRecord> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ContainerLifecycleRecord>> for ContainerLifecycleTable {
    fn from(payload: Vec<ContainerLifecycleRecord>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeployJobTable {
    pub fn new(payload: Vec<DeployJob>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<DeployJob> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<DeployJob> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<DeployJob>> for DeployJobTable {
    fn from(payload: Vec<DeployJob>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TestRunTable {
    pub fn new(payload: Vec<StoredTestRun>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<StoredTestRun> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<StoredTestRun> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<StoredTestRun>> for TestRunTable {
    fn from(payload: Vec<StoredTestRun>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn query_generations(payload: Selection) -> Self {
        Self::QueryGenerations(payload)
    }
    pub fn read_event_log(payload: EventLogRange) -> Self {
        Self::ReadEventLog(payload)
    }
    pub fn check_key_material(payload: KeyMaterialQuery) -> Self {
        Self::CheckKeyMaterial(payload)
    }
    pub fn query_test_runs(payload: TestRunLookup) -> Self {
        Self::QueryTestRuns(payload)
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn generations_queried(payload: GenerationListing) -> Self {
        Self::GenerationsQueried(payload)
    }
    pub fn event_log_read(payload: EventLogPage) -> Self {
        Self::EventLogRead(payload)
    }
    pub fn key_material_checked(payload: KeyMaterialReport) -> Self {
        Self::KeyMaterialChecked(payload)
    }
    pub fn test_runs_queried(payload: TestRunListing) -> Self {
        Self::TestRunsQueried(payload)
    }
    pub fn read_missed(payload: RejectionReport) -> Self {
        Self::ReadMissed(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn record_deploy_submitted(payload: DeploySubmission) -> Self {
        Self::RecordDeploySubmitted(payload)
    }
    pub fn record_phase_transition(payload: DeploymentPhaseEvent) -> Self {
        Self::RecordPhaseTransition(payload)
    }
    pub fn record_generation_activated(payload: ActivationCommit) -> Self {
        Self::RecordGenerationActivated(payload)
    }
    pub fn pin_generation(payload: PinRequest) -> Self {
        Self::PinGeneration(payload)
    }
    pub fn unpin_generation(payload: UnpinRequest) -> Self {
        Self::UnpinGeneration(payload)
    }
    pub fn retire_generation(payload: RetireRequest) -> Self {
        Self::RetireGeneration(payload)
    }
    pub fn record_container_transition(payload: ContainerTransition) -> Self {
        Self::RecordContainerTransition(payload)
    }
    pub fn record_test_run(payload: TestRunRecord) -> Self {
        Self::RecordTestRun(payload)
    }
}

#[rustfmt::skip]
impl DeploySubmission {
    pub fn host(payload: HostDeployment) -> Self {
        Self::Host(payload)
    }
    pub fn user_environment(payload: UserEnvironmentDeployment) -> Self {
        Self::UserEnvironment(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn deploy_submitted(payload: DeployHandle) -> Self {
        Self::DeploySubmitted(payload)
    }
    pub fn phase_recorded(payload: PhaseReceipt) -> Self {
        Self::PhaseRecorded(payload)
    }
    pub fn generation_activated(payload: AppliedActivation) -> Self {
        Self::GenerationActivated(payload)
    }
    pub fn generation_pinned(payload: AppliedPin) -> Self {
        Self::GenerationPinned(payload)
    }
    pub fn generation_unpinned(payload: AppliedUnpin) -> Self {
        Self::GenerationUnpinned(payload)
    }
    pub fn generation_retired(payload: AppliedRetire) -> Self {
        Self::GenerationRetired(payload)
    }
    pub fn container_recorded(payload: ContainerReceipt) -> Self {
        Self::ContainerRecorded(payload)
    }
    pub fn test_run_recorded(payload: AcceptedTest) -> Self {
        Self::TestRunRecorded(payload)
    }
    pub fn write_rejected(payload: RejectionReport) -> Self {
        Self::WriteRejected(payload)
    }
}

#[rustfmt::skip]
impl LoggedEvent {
    pub fn deployment(payload: DeploymentPhaseEvent) -> Self {
        Self::Deployment(payload)
    }
    pub fn cache_retention(payload: CacheRetentionTransitionEvent) -> Self {
        Self::CacheRetention(payload)
    }
    pub fn container(payload: ContainerLifecycleRecord) -> Self {
        Self::Container(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn sema_read_input(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }
    pub fn sema_write_input(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn sema_read_output(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }
    pub fn sema_write_output(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

#[rustfmt::skip]
impl From<Selection> for SemaReadInput {
    fn from(payload: Selection) -> Self {
        Self::QueryGenerations(payload)
    }
}

#[rustfmt::skip]
impl From<EventLogRange> for SemaReadInput {
    fn from(payload: EventLogRange) -> Self {
        Self::ReadEventLog(payload)
    }
}

#[rustfmt::skip]
impl From<KeyMaterialQuery> for SemaReadInput {
    fn from(payload: KeyMaterialQuery) -> Self {
        Self::CheckKeyMaterial(payload)
    }
}

#[rustfmt::skip]
impl From<TestRunLookup> for SemaReadInput {
    fn from(payload: TestRunLookup) -> Self {
        Self::QueryTestRuns(payload)
    }
}

#[rustfmt::skip]
impl From<GenerationListing> for SemaReadOutput {
    fn from(payload: GenerationListing) -> Self {
        Self::GenerationsQueried(payload)
    }
}

#[rustfmt::skip]
impl From<EventLogPage> for SemaReadOutput {
    fn from(payload: EventLogPage) -> Self {
        Self::EventLogRead(payload)
    }
}

#[rustfmt::skip]
impl From<KeyMaterialReport> for SemaReadOutput {
    fn from(payload: KeyMaterialReport) -> Self {
        Self::KeyMaterialChecked(payload)
    }
}

#[rustfmt::skip]
impl From<TestRunListing> for SemaReadOutput {
    fn from(payload: TestRunListing) -> Self {
        Self::TestRunsQueried(payload)
    }
}

#[rustfmt::skip]
impl From<RejectionReport> for SemaReadOutput {
    fn from(payload: RejectionReport) -> Self {
        Self::ReadMissed(payload)
    }
}

#[rustfmt::skip]
impl From<DeploySubmission> for SemaWriteInput {
    fn from(payload: DeploySubmission) -> Self {
        Self::RecordDeploySubmitted(payload)
    }
}

#[rustfmt::skip]
impl From<DeploymentPhaseEvent> for SemaWriteInput {
    fn from(payload: DeploymentPhaseEvent) -> Self {
        Self::RecordPhaseTransition(payload)
    }
}

#[rustfmt::skip]
impl From<ActivationCommit> for SemaWriteInput {
    fn from(payload: ActivationCommit) -> Self {
        Self::RecordGenerationActivated(payload)
    }
}

#[rustfmt::skip]
impl From<PinRequest> for SemaWriteInput {
    fn from(payload: PinRequest) -> Self {
        Self::PinGeneration(payload)
    }
}

#[rustfmt::skip]
impl From<UnpinRequest> for SemaWriteInput {
    fn from(payload: UnpinRequest) -> Self {
        Self::UnpinGeneration(payload)
    }
}

#[rustfmt::skip]
impl From<RetireRequest> for SemaWriteInput {
    fn from(payload: RetireRequest) -> Self {
        Self::RetireGeneration(payload)
    }
}

#[rustfmt::skip]
impl From<ContainerTransition> for SemaWriteInput {
    fn from(payload: ContainerTransition) -> Self {
        Self::RecordContainerTransition(payload)
    }
}

#[rustfmt::skip]
impl From<TestRunRecord> for SemaWriteInput {
    fn from(payload: TestRunRecord) -> Self {
        Self::RecordTestRun(payload)
    }
}

#[rustfmt::skip]
impl From<HostDeployment> for DeploySubmission {
    fn from(payload: HostDeployment) -> Self {
        Self::Host(payload)
    }
}

#[rustfmt::skip]
impl From<UserEnvironmentDeployment> for DeploySubmission {
    fn from(payload: UserEnvironmentDeployment) -> Self {
        Self::UserEnvironment(payload)
    }
}

#[rustfmt::skip]
impl From<DeployHandle> for SemaWriteOutput {
    fn from(payload: DeployHandle) -> Self {
        Self::DeploySubmitted(payload)
    }
}

#[rustfmt::skip]
impl From<PhaseReceipt> for SemaWriteOutput {
    fn from(payload: PhaseReceipt) -> Self {
        Self::PhaseRecorded(payload)
    }
}

#[rustfmt::skip]
impl From<AppliedActivation> for SemaWriteOutput {
    fn from(payload: AppliedActivation) -> Self {
        Self::GenerationActivated(payload)
    }
}

#[rustfmt::skip]
impl From<AppliedPin> for SemaWriteOutput {
    fn from(payload: AppliedPin) -> Self {
        Self::GenerationPinned(payload)
    }
}

#[rustfmt::skip]
impl From<AppliedUnpin> for SemaWriteOutput {
    fn from(payload: AppliedUnpin) -> Self {
        Self::GenerationUnpinned(payload)
    }
}

#[rustfmt::skip]
impl From<AppliedRetire> for SemaWriteOutput {
    fn from(payload: AppliedRetire) -> Self {
        Self::GenerationRetired(payload)
    }
}

#[rustfmt::skip]
impl From<ContainerReceipt> for SemaWriteOutput {
    fn from(payload: ContainerReceipt) -> Self {
        Self::ContainerRecorded(payload)
    }
}

#[rustfmt::skip]
impl From<AcceptedTest> for SemaWriteOutput {
    fn from(payload: AcceptedTest) -> Self {
        Self::TestRunRecorded(payload)
    }
}

#[rustfmt::skip]
impl From<RejectionReport> for SemaWriteOutput {
    fn from(payload: RejectionReport) -> Self {
        Self::WriteRejected(payload)
    }
}

#[rustfmt::skip]
impl From<DeploymentPhaseEvent> for LoggedEvent {
    fn from(payload: DeploymentPhaseEvent) -> Self {
        Self::Deployment(payload)
    }
}

#[rustfmt::skip]
impl From<CacheRetentionTransitionEvent> for LoggedEvent {
    fn from(payload: CacheRetentionTransitionEvent) -> Self {
        Self::CacheRetention(payload)
    }
}

#[rustfmt::skip]
impl From<ContainerLifecycleRecord> for LoggedEvent {
    fn from(payload: ContainerLifecycleRecord) -> Self {
        Self::Container(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadInput> for Input {
    fn from(payload: SemaReadInput) -> Self {
        Self::SemaReadInput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteInput> for Input {
    fn from(payload: SemaWriteInput) -> Self {
        Self::SemaWriteInput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadOutput> for Output {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadOutput(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteOutput> for Output {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteOutput(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaReadInputRoute {
    QueryGenerations,
    ReadEventLog,
    CheckKeyMaterial,
    QueryTestRuns,
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn route(&self) -> SemaReadInputRoute {
        match self {
            Self::QueryGenerations(_) => SemaReadInputRoute::QueryGenerations,
            Self::ReadEventLog(_) => SemaReadInputRoute::ReadEventLog,
            Self::CheckKeyMaterial(_) => SemaReadInputRoute::CheckKeyMaterial,
            Self::QueryTestRuns(_) => SemaReadInputRoute::QueryTestRuns,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaReadOutputRoute {
    GenerationsQueried,
    EventLogRead,
    KeyMaterialChecked,
    TestRunsQueried,
    ReadMissed,
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn route(&self) -> SemaReadOutputRoute {
        match self {
            Self::GenerationsQueried(_) => SemaReadOutputRoute::GenerationsQueried,
            Self::EventLogRead(_) => SemaReadOutputRoute::EventLogRead,
            Self::KeyMaterialChecked(_) => SemaReadOutputRoute::KeyMaterialChecked,
            Self::TestRunsQueried(_) => SemaReadOutputRoute::TestRunsQueried,
            Self::ReadMissed(_) => SemaReadOutputRoute::ReadMissed,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaWriteInputRoute {
    RecordDeploySubmitted,
    RecordPhaseTransition,
    RecordGenerationActivated,
    PinGeneration,
    UnpinGeneration,
    RetireGeneration,
    RecordContainerTransition,
    RecordTestRun,
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn route(&self) -> SemaWriteInputRoute {
        match self {
            Self::RecordDeploySubmitted(_) => SemaWriteInputRoute::RecordDeploySubmitted,
            Self::RecordPhaseTransition(_) => SemaWriteInputRoute::RecordPhaseTransition,
            Self::RecordGenerationActivated(_) => {
                SemaWriteInputRoute::RecordGenerationActivated
            }
            Self::PinGeneration(_) => SemaWriteInputRoute::PinGeneration,
            Self::UnpinGeneration(_) => SemaWriteInputRoute::UnpinGeneration,
            Self::RetireGeneration(_) => SemaWriteInputRoute::RetireGeneration,
            Self::RecordContainerTransition(_) => {
                SemaWriteInputRoute::RecordContainerTransition
            }
            Self::RecordTestRun(_) => SemaWriteInputRoute::RecordTestRun,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaWriteOutputRoute {
    DeploySubmitted,
    PhaseRecorded,
    GenerationActivated,
    GenerationPinned,
    GenerationUnpinned,
    GenerationRetired,
    ContainerRecorded,
    TestRunRecorded,
    WriteRejected,
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn route(&self) -> SemaWriteOutputRoute {
        match self {
            Self::DeploySubmitted(_) => SemaWriteOutputRoute::DeploySubmitted,
            Self::PhaseRecorded(_) => SemaWriteOutputRoute::PhaseRecorded,
            Self::GenerationActivated(_) => SemaWriteOutputRoute::GenerationActivated,
            Self::GenerationPinned(_) => SemaWriteOutputRoute::GenerationPinned,
            Self::GenerationUnpinned(_) => SemaWriteOutputRoute::GenerationUnpinned,
            Self::GenerationRetired(_) => SemaWriteOutputRoute::GenerationRetired,
            Self::ContainerRecorded(_) => SemaWriteOutputRoute::ContainerRecorded,
            Self::TestRunRecorded(_) => SemaWriteOutputRoute::TestRunRecorded,
            Self::WriteRejected(_) => SemaWriteOutputRoute::WriteRejected,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(SemaWriteInputRoute),
    ReadInput(SemaReadInputRoute),
    WriteOutput(SemaWriteOutputRoute),
    ReadOutput(SemaReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
#[rustfmt::skip]
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    SemaWriteInputRoute::RecordDeploySubmitted => {
                        "SemaWriteInputRecordDeploySubmitted"
                    }
                    SemaWriteInputRoute::RecordPhaseTransition => {
                        "SemaWriteInputRecordPhaseTransition"
                    }
                    SemaWriteInputRoute::RecordGenerationActivated => {
                        "SemaWriteInputRecordGenerationActivated"
                    }
                    SemaWriteInputRoute::PinGeneration => "SemaWriteInputPinGeneration",
                    SemaWriteInputRoute::UnpinGeneration => {
                        "SemaWriteInputUnpinGeneration"
                    }
                    SemaWriteInputRoute::RetireGeneration => {
                        "SemaWriteInputRetireGeneration"
                    }
                    SemaWriteInputRoute::RecordContainerTransition => {
                        "SemaWriteInputRecordContainerTransition"
                    }
                    SemaWriteInputRoute::RecordTestRun => "SemaWriteInputRecordTestRun",
                }
            }
            Self::ReadInput(route) => {
                match route {
                    SemaReadInputRoute::QueryGenerations => {
                        "SemaReadInputQueryGenerations"
                    }
                    SemaReadInputRoute::ReadEventLog => "SemaReadInputReadEventLog",
                    SemaReadInputRoute::CheckKeyMaterial => {
                        "SemaReadInputCheckKeyMaterial"
                    }
                    SemaReadInputRoute::QueryTestRuns => "SemaReadInputQueryTestRuns",
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    SemaWriteOutputRoute::DeploySubmitted => {
                        "SemaWriteOutputDeploySubmitted"
                    }
                    SemaWriteOutputRoute::PhaseRecorded => "SemaWriteOutputPhaseRecorded",
                    SemaWriteOutputRoute::GenerationActivated => {
                        "SemaWriteOutputGenerationActivated"
                    }
                    SemaWriteOutputRoute::GenerationPinned => {
                        "SemaWriteOutputGenerationPinned"
                    }
                    SemaWriteOutputRoute::GenerationUnpinned => {
                        "SemaWriteOutputGenerationUnpinned"
                    }
                    SemaWriteOutputRoute::GenerationRetired => {
                        "SemaWriteOutputGenerationRetired"
                    }
                    SemaWriteOutputRoute::ContainerRecorded => {
                        "SemaWriteOutputContainerRecorded"
                    }
                    SemaWriteOutputRoute::TestRunRecorded => {
                        "SemaWriteOutputTestRunRecorded"
                    }
                    SemaWriteOutputRoute::WriteRejected => "SemaWriteOutputWriteRejected",
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    SemaReadOutputRoute::GenerationsQueried => {
                        "SemaReadOutputGenerationsQueried"
                    }
                    SemaReadOutputRoute::EventLogRead => "SemaReadOutputEventLogRead",
                    SemaReadOutputRoute::KeyMaterialChecked => {
                        "SemaReadOutputKeyMaterialChecked"
                    }
                    SemaReadOutputRoute::TestRunsQueried => {
                        "SemaReadOutputTestRunsQueried"
                    }
                    SemaReadOutputRoute::ReadMissed => "SemaReadOutputReadMissed",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Sema(SemaObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::SemaWriteInput;
    pub type WriteOutput = super::SemaWriteOutput;
    pub type ReadInput = super::SemaReadInput;
    pub type ReadOutput = super::SemaReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::SemaWriteInput for SemaWriteInput {}

#[rustfmt::skip]
impl triad_runtime::SemaWriteOutput for SemaWriteOutput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadInput for SemaReadInput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadOutput for SemaReadOutput {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SemaEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
